var today_in_history = {
    "0101": {"404":"Last gladiator competition in Rome", "1724":"Daniel Gabriel Fahrenheit, a glassblower in London, proposes the Farenheit temperature scale", "1896":"X-rays are discovered by German Wilhelm Rontgen"},
    "0102": {"1492":"The Spanish Reconquista ends as Ferdinand II of Spain conquers the last Muslim ruler in the Iberian Peninsula", "1906":"American Willis Carrier patents the world's first air conditioner", "1959":"Luna 1 of USSR is the first spacecraft to leave Earth's gravity. Reaches the Moon and goes in heliocentric orbit"},
    "0103": {"1823":"Mexico grants Stephen F. Austin land in Texas. 11 years later to the day he is thrown in prison in Mexico City", "1925":"Benito Mussolini proclaims himself dictator of Italy. He dissolves parliament", "1993":"Over 7 million Black South Africans have their citizenship restored to vote in the first non-racial polls in April"},
    "0104": {"1887":"Thomas Stevens is the first person to bicycle around the world. Around 13,500 miles on those bikes with the big front wheel. (I'm baffled)", "1947":"Technetium is announced in Italy, the first artificially synthesized chemical element", "2007":"Nancy Pelosi first woman elected as US Speaker of House"},
    "0105": {"1822":"Central America from Guatemala to Costa Rica annexed into the Mexican Empire", "1892":"First photograph of the aurora borealis (northern lights) by two Germans in Norway", "1969":"Venera 5 (USSR), a space probe, is launched. Later becomes the first successful object landed on another planet, Venus"},
    "0106": {"1838":"Samuel Morse and Alfred Vail demonstrate the telegraph in New Jersey", "1980":"GPS Epoch starts. All satellites clock's are synced based on seconds after January 5th of this year", "1987":"Astronomers at UC Berkeley believe they witnessed the first birth of a galaxy"},
    "0107": {"1930":"Francium is the last naturally occurring chemical element to be discovered in France", "1999":"US President Bill Clinton's impeachment trial starts in Senate for lying about affair", "2024":"Michael Toriello becomes the first player to get a perfect score, a 3, on Today in History"},
    "0108": {"1790":"George Washington gives first State of the Union Address", "1926":"Abdulaziz Ibn Saud becomes King of Nejd and Hejaz, later to become Saudi Arabia", "1964":"US President Lyndon B. Johnson gives famous speech declaring 'War on Poverty'"},
    "0109": {"1799":"British Prime Minister introduces income tax to raise funds for war against Napoleon", "1967":"New Orleans NFL team named Saints", "2001":"iTunes introduced by Apple to organize and play digitial music and videos"},
    "0110": {"1870":"Standard Oil is incorporated by John D. Rockefeller", "1951":"United Nations Headquarters open in Manhattan, New York", "2022":"First black woman minted on a US Quarter. Commemorates poet Maya Angelou"},
    "0111": {"1569":"First National Lottery takes place in England. Winner earned a prize of 5000 pounds", "1922":"First insulin injection on humans to treat diabetes performed by Canadian Frederick Banting", "2007":"J.K. Rowling finishes the 7th and last Harry Potter book in Edinburgh, Scotland"},
    "0112": {"1913":"Josef Dzhugashvili signs himself Josef Stalin, meaning 'Man of Steel' for the first time in a letter.", "1948":"First UK Supermarket opens by the London Cooperative Society in Manor Park", "2010":"Devistating earthquake in Haiti kills 160,000 people and destroys the capital, Port-au-Prince"},
    "0113": {"1930":"First Mickey Mouse comic debuts", "1948":"First country music TV show, 'Midwestern Hayride' premieres in Cincinnati, Ohio", "2021":"Oldest known cave painting of an animal, a pig, at 45,000 years old discovered in Sulawesi, Indonesia"},
    "0114": {"1690":"The clarinet is invented in Nurnberg, Germany", "1953":"Yugoslavia elects their first president, Marshal Tito", "1963":"George Wallace sworn as Governor of Alabama. Chants 'Segregation now; segregation tomorrow; segregation forever!'"},
    "0115": {"1797":"First top hat worn by John Etherington of London", "1945":"First betatron pictures of nuclear implosion at Los Alamos Lab in New Mexico", "2009":"Pilot Chesley Sullenberger crash lands plane on the Hudson River. Everyone survived"},
    "0116": {"1547":"Ivan the Terrible crowns himself first Tsar of Russia", "1919":"The 18th Amendment added to the US Constitution. Prohibition, making alcohol illegal, takes effect", "1970":"Muammar Gaddafi takes control over Libya after a 4 month long coup"},
    "0117": {"1929":"Popeye makes first comic strip appearance", "1961":"US President Eisenhower delivers TV farewell address where he warns against the 'military-industrial complex'", "1995":"Los Angeles Rams announce they are moving to St. Louis. They come back 21 years later"},
    "0118": {"1871":"The Second German Empire (Reich) proclaimed by Kaiser Wilhelm I", "1944":"First Chinese naturalized US citizen since the repeal of the Exclusion Acts (lasted 62 years)", "1993":"First national observation of Martin Luther King Jr. holiday"},
    "0119": {"1955":"US President Eisenhower is the has the first new conference filmed on TV", "1974":"Notre Dame beats UCLA in basketball ending their 88-game win streak", "2013":"Lance Armstrong admits to doping during all seven of his Tour de France victories"},
    "0120": {"1869":"Elizabeth Cady Stanton becomes the first woman to testify before US Congress", "1945":"Franklin D. Roosevelt sworn in for the first and only fourth term as US President", "1979":"One million Iranians march to show support for exiled Ayatollah Khomeini"},
    "0121": {"1793":"The French Revolution executes King Louis XVI by guillotine", "1979":"Pluto moves closer and then Neptune becomes the furthest planet. Pluto later demoted", "2017":"Two million women protest the inauguration of President Donald Trump"},
    "0122": {"1905":"'Bloody Sunday' in Russia. Protesting the Tsar, soldiers kill or wound thousands in St. Petersburg", "1964":"World's largest cheese made in Wisconsin. Cheddar Cheese weighed 34,591 lbs (15,723 kg)", "2006":"Evo Morales is inaugurated as President of Bolivia, the first indigenous president there"},
    "0123": {"1368":"Ming Dynasty begins after Zhu Yuanzhang ascends to the throne of China", "1849":"First woman in US to earn a medical degree. Graduated from NY Geneva Medical College", "2015":"Klay Thompson scores the most points in one quarter, 37"},
    "0124": {"1848":"Gold is found by James Marshall at Sutter's Mill in California, starting the gold rush", "1935":"First canned beer sold by American company Krueger Brewing Co.", "1984":"Apple launches revolutionary Macintosh personal computer"},
    "0125": {"1802":"Napoleon Bonaparte elected president of Italian Republic", "1924":"First Winter Olympic Games in Chamonix, France", "1985":"Joe Damiani met Robin Broth (famous people)"},
    "0126": {"1784":"Benjamin Franklin writes a letter with disappointment in the bald eagle being the US bird. He wanted the turkey", "1905":"World's largest diamond discovered in South Africa. Weighs 3,106 carats (621.2 g)", "1969":"First Australian Open Women's tennis final. Margaret Court wins"},
    "0127": {"1785":"First US State University, the University of Georgia, founded in Athens", "1825":"US Congress approves Oklahoma as 'Indian Territory', starting the Trail of Tears and forced relocation of Eastern Indian tribes", "1945":"Soviets liberate Auschwitz in Poland, now commemorated as International Holocaust Remembrance Day"},
    "0128": {"1855":"First locomotive runs from the Atlantic to the Pacific Oceans on the Panama Railway", "1986":"USS Challenger explodes 73 seconds after takeoff on its way to space. All 7 crew killed", "2021":"Mittens worn by Bernie Sanders raise $1.8 million for charity after pictures go vial"},
    "0129": {"1595":"First performance of Shakespeare's Romeo and Juliet", "1850":"Henry Clay drafts the Compromise of this year, temporarily diffusing tensions between the north and south USA", "1996":"President of France, Jacques Chirac says France will no longer test nuclear weapons after public outcry"},
    "0130": {"1815":"Thomas Jefferson re-establishes the burned down Library of Congress with his 6,500 volumes", "1835":"First attempted assassination of US President. Missed Andrew Jackson", "1948":"Mahatma Gandhi assassinated by Hindu extremist"},
    "0131": {"1905":"First automobile to pass 100 mph driven by Arthur MacDonald in Daytona Beach, Florida", "1964":"Rigged Ghanan election sees 99% vote to make a one-party state and Kwame Nkrumah president for life", "2020":"Brexit has the United Kingdom formally withdraw from the European Union"},
    "0201": {"1884":"First volume of Oxford English Dictionary posted. Called A-Ant", "1951":"First television broadcast of a nuclear explosion. Bomb was in Nevada. Broadcast in Los Angeles", "2014":"Peyton Manning wins his NFL record 5th Most Valuable Player award"},
    "0202": {"1887":"First Groundhog Day (American holiday) in Punxsutawney, Pennsylvania", "1913":"Grand Central Terminal opens in New York City", "2009":"RuPaul's Drag Race premieres"},
    "0203": {"1488":"Portuguese explorer Barolomeu Dias's boat is first Europeans to land in South Africa", "1913":"Federal Income Tax ratified in US in the 16th Amendment", "1986":"Pixar breaks off as independent company with help from Steve Jobs"},
    "0204": {"1789":"George Washington elected first US President. John Adams first VP","1948":"Formally called Ceylon, Sri Lanka declares independence from the UK","2004":"Facebook launched by Mark Zuckerberg"},
    "0205": {"1900":"Treaty signed with UK gives USA full control over the Panama Canal", "1971":"Third manned Moon expedition. Apollo 14 astronauts walk on mood for 4 hours", "2016":"Cyber hackers steal $101 million from US Federal Reserve. Noticed after a typo"},
    "0206": {"1899":"Spanish American War ends. Spain cedes Philippines, Puerto Rico, and Guam to the US", "1956":"French Prime Minister Guy Mollet pelted with tomatoes in Algeria", "2014":"Last time Jay Leno hosted The Tonight Show"},
    "0207": {"1817":"Baltimore becomes the first US city lit by gas street lamps", "1928":"Bert Hinkler takes off to become first solo flight from UK to Australia. Took 15 days.", "2013":"Azerbaijan's first satellite made it to space"},
    "0208": {"1627":"First reported use of gunpowder for mining in Slovakia","1935":"First election where women can vote in Turkey", "1986":"Spud Webb, 5 foot 7 inches (170 cm), wins the dunk contest"},
    "0209": {"1897":"Kingdom of Benin annexed by British Empire, ending 900 years of rule", "1964":"Beatles perfrom first live US TV performance on Ed Sullivan Show", "2014":"Oldest known star discovered with Magellan Telescope in Chile. Estimated to be 13.7 billion years old"},
    "0210": {"1763":"Treaty of Paris ends French-Indian War. France loses many territories including Canada to the UK an Louisiana to Spain", "1933":"First singing telegram (delivery of message with a singing artist) from Postal Telegram Co NYC", "2021":"Thought to be oldest known instrument is found. A conch shell turned horn 17,000 years old in the Pyranees, France"},
    "0211": {"1935":"Record low temperature ever in Africa in Morocco -11F (-23.9C)", "1945":"FDR, Winston Churchill, and Joseph Stalin sign the Declaration of Liberated Europe -- to protect Europe at the Yalta Conference", "1990":"Nelson Mandela freed after 27 years in prison"},
    "0212": {"1793":"First fugitive slave act passed. In US, Northerners must return runaway slaves.", "1914":"First feature film filmed in Hollywood, The Squaw Man", "1983":"First 200 mph (320 km/h) lap in the Daytona 500 by Cale Yarborough"},
    "0213": {"1258":"Baghdad falls to the Mongols, arguably ending the Islamic Golden Age", "1960":"First nuclear bomb detonated by France in Algeria. Becomes the 4th nuclear nation", "2009":"UNIX time (time since Jan 1 1970) hits 1,234,567,890 seconds. Do some math :)"},
    "0214": {"1844":"First European to discover Lake Tahoe, Nevada/California is John C. Fremont", "1929":"St. Valentines Day Massacre. 7 gangsters killed on Al Copone's orders", "1991":"Silence of the Lambs, is released in theaters"},
    "0215": {"1932":"Eddie Eagan becomes the only athlete to win a gold in Summer and Winter Olympic Sports. Boxing and bobsled", "1950":"Original Cinderella by Walt Disney premieres in Boston", "1992":"Jeffrey Dahmer declared sane and guilty of killing 15 boys"},
    "0216": {"1932":"First patent for a tree granted to James Markham for a peach tree", "1959":"Fidel Castro sworn in as Prime Minister of Cuba", "2013":"Angelina Jolie has preventative double masectomy after learning she has defective BRCA1 gene"},
    "0217": {"1801":"Thomas Jefferson elected president after House vote breaks tie", "1959":"First weather satellite, the Vanguard 2, launched from Florida", "1996":"Gary Kasparov beats IBM's Deep Blue Computer in Chess. Last time humans were better..."},
    "0218": {"1861":"Jefferson Davis inagurated as the President of the Confederate States of America in Alabama","1954":"First church of scientology opens in Los Angeles, CA", "2001":"Robert Hanssen of the FBI arrested for spying for the USSR and later Russia"},
    "0219": {"1914":"Five year old mailed by train within Idaho 73 miles to her grandparents house", "1942":"US President FDR orders the detention and internment of Japanese-American citizens. Moved ~ 120,000 people", "2008":"Toshiba HD DVD is officially recalled, losing the format war against Sony's Blu-Ray Disc"},
    "0220": {"1937":"First test flight of a car/plane hybrid vehicle", "1959":"Jimi Hendrix plays his first gig in a synagogue basement in Seattle. Fired from the band after one set for 'wild playing'", "1991":"Python coding language released by Guido van Rossum of the Netherlands"},
    "0221": {"1804":"First train runs in Wales. It averaged less than 10 mph", "1878":"First telephone directory (phonebook) issued in Connecticut", "1958":"British graphic artist Gerald Holtom designs the peace symbol"},
    "0222": {"1935":"First Hollywood interracial dance couple between Shirley Temple and Bill Robinson", "1980":"Miracle on Ice. US hockey team beats heavily favored Soviet team 4-3 in the Olympics to eventually win gold in New York", "1997":"First cloned mammal, Dolly the Sheep, announced in Scotland"},
    "0223": {"1455":"First Gutenberg Bible published", "1945":"US Marines raise flag on Iwo Jima. Photo wins the Pulitzer Prize, and later inspires a War Memorial Sculpture", "1987":"First supernova able to be seen with the naked eye since 1604. Star was 168,000 light-years away"},
    "0224": {"1868":"First impeachment vote succeeds of a US President, Andrew Johnson. Senate later votes to not acquit", "1998":"Elton John is knighted by Queen Elizabeth II", "2020":"Mahathir bin Mohamad resigns at 94 years old as Prime Minister of Malaysia only to be reinstated as interim prime minister that day"},
    "0225": {"1836":"Samuel Colt patents first multi-shot revolving-cylinder revolver, enabling the firearm to be fired multiple times without reloading", "1870":"Hiram Revels first black US Senator elected in Mississippi", "1998":"First legal brothel opens in Switzerland"},
    "0226": {"1935":"First demonstration of RADAR by Robert Watson-Watt", "1955":"First bail out of a plane moving supersonic speeds: George F. Smith moving mach 1.05 (750+ mph)", "2020":"For first time in living memory, Saudi Arabia bans overseas pilgrims from Mecca and Medina for fear of covid-19"},
    "0227": {"1812":"Argentinian flag first raised in Rosario. Flag created by Manuel Belgrano", "1951":"Twenty Second Amendment ratified limiting US Presidential terms to two terms", "2013":"Pope Benedict gives his farewell address, retiring at 94 years old"},
    "0228": {"1947":"This day massacre. Taiwanese uprising violently ended by Republic of China government. 18-28 thousand people die", "1953":"Double Helix structure of DNA discovered by Francis Crick and James Watson", "2013":"Brains of two rats electrically connected allowing them to share information such as when to press a lever for a reward"},
    "0229": {"1692":"(hint: leap day so all years are multiples of 4) First people accused of witchcraft in Salem, Massachusetts", "1940":"First black oscar winner is Hattie McDaniel from her role in Gone with the Wind", "1960":"First playboy club (nightclub) opened in Chicago"},
    "0301": {"1845":"US President John Tyler annexes the Republic of Texas (incorporates into the Union)", "1872":"Yellowstone becomes the world's first National Park", "1973":"Dark Side of the Moon by Pink Floyd released"},
    "0302": {"1836":"Republic of Texas declares independence from Mexico", "1965":"The Sound of Music premieres starring Julie Andrews and Christopher Plummer", "2016":"Scott Kelly and Mikhail Kornienko return to Earth after a record 340 days in the International Space Station"},
    "0303": {"1861":"Alexander II of Russia frees the serfs granting them full rights as citizens", "1955":"Elvis Presley makes his TV debut on Louisiana Hayride", "1991":"Rodney King was brutally beaten by Los Angeles Police. Riots began when all officers were acquitted."},
    "0304": {"1841":"US President William Henry Harrison gives the longest inauguration speech in the freezing cold. Dies just 31 days later, speculated from the speech", "1929":"Charles Curtis becomes the first Native American Vice President of the USA. From the Kaw and Osage Nation in Kansas. VP to Herbert Hoover", "2007":"First national election in the world to allow remote electronic voting takes place in Estonia"},
    "0305": {"1841":"First US Senate filibuster (where one keeps talking to postpone a vote) begins. Lasts 6 days to March 11", "1974":"First performance in 3000 years of world's oldest known song, Hymn to Nikkal, from present day Syria 1400 BCE, performed at Berkeley University", "2019":"Kylie Jenner becomes the world's youngest-ever billionaire at 21 years old"},
    "0306": {"1836":"Battle of the Alamo ends with Mexican forces overwhelming Texan forces", "1985":"Mike Tyson knocks out his first professional opponent in 1 minute 47 seconds at 18 years old", "2018":"World's oldest message in a bottle found in Australia, thrown from a German ship 132 years previous"},
    "0307": {"1876":"Alexander Graham Bell patents the telephone in the US", "1936":"Adolf Hitler breaks Treaty of Paris by sending troops into the Rhineland", "2019":"Queen Elizabeth II shares her first Instagram Post. A letter written to her distant ancestor Prince Albert"},
    "0308": {"1919":"First celebration of International Women's Day. Started in Europe", "1973":"World's highest tunnel, the Eisenhower Tunnel, opens at 11,013 feet outside Denver, Colorado", "2014":"Malaysia Airlines Flight MH370 disappears completely with 239 people on it"},
    "0309": {"1945":"Tokyo is attacked by 120,000 fire bombs in World War II. Japan refuses to surrender", "1974":"Hiroo Onoda, Japanese soldier, surrenders in the Phillippines after 29 years of not hearing World War II ended", "1998":"Dr. Dre signs then unknown rapper, Eminem, to Aftermath Records"},
    "0310": {"1849":"Abraham Lincoln applies for a patent for a device to lift a boat over obstacles in a river. He is the only US president to apply for a patent", "1948":"First civilian (non-military) to break the sound barrier is Herbert Hoover (not the president). Traveled 703 mph (1127 kmh)", "2020":"Russian Parliament passes a law that President Vladamir Putin can hold office for life"},
    "0311": {"1888":"The Great Blizzard of this year dumped as much as 55 inches of snow in the Northeast US. So many people were stranded on above ground trains in New York City, this partially led to building the Subway.", "1958":"US Airforce accidentally drops a nuclear bomb on a farm in South Carolina. Luckily nobody was injured and it was missing the radioactive payload for transport. Still left a 75 foot crater", "2006":"Michelle Bachelet inagurated as the first female president of Chile"},
    "0312": {"1894":"Coca Cola sold in bottles for the first time. Originally just a fountain drink", "1933":"US Predient Franklin Delanor Roosevelt has his first fireside chat. He spoke like a conversation over radio broadcast to the American people", "1994":"Church of England ordains its first ever female priests. There were 33 today"},
    "0313": {"1921":"Mongolia declares independence from China", "1965":"Eric Clapton breaks off from the Yardbirds to become a solo artist", "1986":"Microsoft first initial public offering (sale of stocks). $1,000 invested then would be worth $3.23 million today"},
    "0314": {"1794":"Eli Whitney pattens the cotton gin in the US. This makes the cotton industry extremely profitable in the South and unfortunately contributed to the increase in slavery", "1900":"Dutch botanist rediscovers Gregor Menel's laws of heredity and genetics 40 years after originally discovered", "1990":"Mikhail Gorbachev elected last president of the Soviet Union"},
    "0315": {"44":"Julius Caesar stabbed to death by 40 senators (answer is in BCE, but just write the number)", "1906":"Grand Duchy of Finland (technically in the Russian Empire) first European country to allow women to vote", "1972":"The Godfather premieres in New York City"},
    "0316": {"1861":"Sam Houston ousted as governer of Texas by Edward Clark because he wouldn't swear allegiance to the Confederacy", "1926":"First liquid-fueled rocket launched by Robbert H. Goddard in the US. The rocket went 60 mph and went 41 feet high 184 feet away (96kmh/12m/56m", "2012":"Notable figures like George Clooney and Martin Luther King III arrested in the US for protesting support of humanitarian aid to go to Sudan"},
    "0317": {"432":"Saint Patrick kidnapped by pirates from Roman-controlled Britain and taken to Ireland. Credited for bringing Christianity to Ireland. Celebrated still!", "1861":"Italy is unified for the first time under King Victor Emmanuel II", "2014":"Republic of Crimea declared, separating from Ukraine. Within days Russia had complete military control"},
    "0318": {"1952":"First cataracts surgery placed a plastic lens, restoring vision to the blind in Pennsylvania, USA", "1965":"First 'Space Walk' performed by USSR Cosmonaut Alexei Leonov. Left spacecraft for 12 minutes", "1995":"Michael Jordan announces he is coming back to the NBA after 17 months of playing for the MLB"},
    "0319": {"1920":"The US Senate rejects the Treaty of Versailles for the second time rejecting the League of Nations (founded by US President Woodrow Wilson)", "1972":"India and newly-separated-from-Pakistan Bangladesh sign a Friendship Treaty", "1993":"NFL Owners take away the right for the Super Bowl to be in Phoenix in 2 years because the state of Arizona refused to recognize Martin Luther King Day"},
    "0320": {"1800":"Alessandro Volta of Italy reports the discovery of the electric battery", "1985":"Libby Riddles becomes the first female winner of the Iditarod Sled Dog Race in Alaska", "2019":"Walt Disney Company buys 21st Century Fox for $71 billion"},
    "0321": {"1925":"Tennessee signs Butler Act, banning the teaching of the Theory of Evolution", "1952":"Attributed as the first Rock & Roll Concert, 12,000 attend The Moondog Coronation Ball in Cleveland, Ohio", "2006":"First tweet sent out by founder Jack Dorsey: just setting up my twttr"},
    "0322": {"1765":"Stamp Act passed, the first direct British tax on American colonists. Spoiler Alert: they didn't like it", "1960":"First patent for lasers to Arthur Schawlow and Charles Townes", "2012":"Over 200,000 protest tuition hikes in Montreal, Canada"},
    "0323": {"1775":"Patrick Henry declares 'Give me Liberty or Give me Death!' in a speech to allocate troops for the Revolutionary Army", "1936":"First intravenous injection of radioisotope to treat cancer (direct injection of radiation) by Joseph G. Hamilton", "1996":"First direct presidential election (as opposed to a ballot of deputies) in Taiwan. Lee Teng-hui wins."},
    "0324": {"1603":"England and Scotland 'Union of the Crowns.' First time under same monarch, King James I of Scotland", "1882":"German Robert Koch first to isolate bacteria, in particular one that causes tuberculosis. Leads to medical acceptance of germ theory", "2005":"US Version of the Office premieres on NBC"},
    "0325": {"1807":"Slave trade abolished throughout the British Empire", "1934":"First Masters golf tournament in Augusta, Georgia. Won by Horton Smith", "2006":"After a rigged Belarussian election, the opposing candidate is arrested protesting. The leader is still in power and every election since has rigged claims"},
    "0326": {"1820":"Joseph Smith has his First Vision in New York, according to Mormon scholars", "1953":"Dr. Jonas Salk announces successful Polio vaccine", "2018":"Porn star, Stormy Daniels claims she had an affair with President Donald Trump and was threatened to keep quiet"},
    "0327": {"1952":"Singin' in the Rain premieres", "1977":"Worst airplane disaster ever. Two passenger jets collide in midair killing 583 in Tenerife, a Spanish island", "2005":"Grey's Anatomy premieres on ABC"},
    "0328": {"1939":"Spanish Civil War ends as Madrid falls to the Nationalists and Francisco Franco", "1989":"The Louvre Pyramid, designed by I.M. Pei, is inaugurated by French President Francois Mitterrand", "2018":"First time Kim Jong-Un leaves North Korea. Visits Chinese President Xi"},
    "0329": {"1795":"Ludwig van Beethoven has his debut performance at 24 years old in Vienna", "1929":"First telephone installed in the Oval Office in the White House for Herbert Hoover", "1974":"Chinese farmers discover 8,000 terracotta soldiers in the tomb of the first Qin Emporer"},
    "0330": {"1867":"US purchases Alaska from Russia for $7.2 million at the time, roughly 2 cents an acre", "1979":"British politician killed by Irish National Liberation Army by a car bomb", "2001":"At 15 years old, Michael Phelps becomes the youngest male to set a world record, breaking the 200m butterfly record with a time of 1 min 54.92 sec"},
    "0331": {"1814":"Napoleon finally defeated by the Sixth Coalition of other European powers. The Russian and Prussian leaders march on Paris", "1889":"Eiffel Tower opens in Paris. At 300m tall, it's the tallest building in the world", "2001":"First time brothers come in first and second in F1 race. Michael and Ralf Schumacher in the Brazilian Grand Prix"},
    "0401": {"391":"Happy April Fools Day! All of the years are flipped. So 1982 would be 2891. Bobby Jones wins first golf tournament of the first golf Grand Slam (winning all 4 majors in the same year)", "6791":"Steve Wozniak and Steve Jobs found Apple in the garage of Jobs' parents", "4002":"Google launches Gmail. Today has 1.5 billion active users"},
    "0402": {"1866":"President Andrew Johnson declares the US Civil War is over in all states but Texas", "1917":"Jeannette Rankin, the first woman in the US House of Representatives, starts her term representing Montana", "1966":"USSR spacecraft, Luna 10, becomes the first to orbit the moon"},
    "0403": {"1860":"Pony Express starts in US. Letters go through relays throughout the country, able to send letters from New York to California in lightning fast 10 days", "1948":"US President Truman signs the Marshall Plan, sending 5 billion dollars to rebuild post WWII Western Europe", "1973":"First mobile phone call. Motorola employee Marin Cooper makes call from Manhattan to the HQ in New Jersey"},
    "0404": {"1958":"The CND Peace symbol, (aka hippie peace symbol), displayed for first time in public in London", "1968":"Martin Luther King Jr. assassinated in Memphis, Tennessee. Riots break out in over 100 cities", "1975":"Microsoft founded by Bill Gates and Paul Allen in Albuquerque, New Mexico"},
    "0405": {"1792":"First US Presidential veto denies the North making more seats in the House. Deemed unconstitutional, setting a precedent", "1951":"Julius and Ethel Rosenberg are sentenced to death for spying on American military intelligence for the Soviet Union", "2005":"Peruvian President Alberto Fujimori dissolves Congress, reorganizes the high Judicial Court, and gives the Executive Branch complete power"},
    "0406": {"1896":"First Modern Olympics revived after 1500 years in Athens, Greece. 13 nations compete", "1906":"First animated cartoon released on film. Called The Humorous Phases of Funny Faces", "1994":"Rwandan and Burundian Presidents shot down in the same airplane, ending peace talks and starting the Rwandan genocide"},
    "0407": {"1923":"First successful brain tumor removal surgery with local anesthetic in New York hospital", "1967":"Gangsters Henry Hill and Tommy DeSimone rob Air France in JFK Airport, stealing $420,000", "1992":"Bosinan-Serb Republic declares independence. Incorporated 3 years later into Bosnia and Herzegovina"},
    "0408": {"1820":"Famous Ancient Greek statue, Venus de Milo, discovered by Greek farmer", "1960":"Civil Rights Bill passed by Congress. Prohibits any impediment of voting based on discriminatory laws", "1993":"Carlos Baerga hits the first pair of switch hit home runs (one righty, one lefty) in the same inning"},
    "0409": {"1865":"Robert E. Lee surrenders with ~27,000 troops, ending the US Civil War", "1967":"The most common aircraft today, the Boeing 737 makes its maiden flight (first flight)", "2003":"Bagdhad, capital of Iraq, falls to US troops. Saddam Hussein is nowhere to be found"},
    "0410": {"1925":"The Great Gatsby by F. Scott Fitzgerald published", "1947":"Jackie Robinson signs first Major League contract with the Brooklyn Dodgers", "2019":"First ever photo of a black hole announced. It is 55 million light-years away and is 6.5 billion times the mass of Earth"},
    "0411": {"1900":"US Navy purchases the first modern submarine. Designed and built by John Philip Holland", "1976":"Apple-1 Personal Computer released by Steve Wozniak of Apple. First product sold by Apple. Modern equivalent of $3,400", "1989":"First playoff goal from a hockey goalie by Ron Hextall of the Philadelphia Flyers"},
    "0412": {"1861":"Fort Sumter attacked in South Carolina by the Confederacy, starting the US Civil War", "1945":"Harry S. Truman inaugurated as US President after the death of FDR earlier that day", "1955":"Polio Vaccine announced successful. The year previous Polio was the leading cause of death by infectious disease in children"},
    "0413": {"1944":"Infamous Transport No. 71. 1,500 French Jews arrive at Auschwitz. 1,260 killed on arrival", "1990":"The Pat Sajak late night talk show ends", "1994":"Japanese discovered asteroid named 7307 Takei after Star Trek actor, George Takei"},
    "0414": {"1865":"President Abraham Lincoln shot in Ford's Theater. Dies a day later","1912":"The Titanic hits the iceberg at 11:40 pm. Sinks the next day", "1993":"Bill Nye the Science Guy debuts on KCTS-TV"},
    "0415": {"1927":"Babe Ruth breaks his own single season Homerun record with 60. Stands for 34 years", "1947":"First African American baseball player, Jackie Robinson, plays his first game for the Brooklyn Dodgers", "2019":"Fire breaks out in Notre Dame in Paris. Spire and roof are completely destroyed"},
    "0416": {"1705":"Isaac Newton knighted by Queen Anne in Cambridge", "1912":"Harriet Quimby is the first women to fly across the English Channel", "2018":"Kendrick Lamar is first rapper and non-classical or jazz musician to win the Pulizer Prize with Damn"},
    "0417": {"1958":"Brussels World Fair opens. First World Fair since World War II ended", "1982":"Constitution Act signed between England and Canada gives Canada full independence to change its constitution", "2012":"Europe's oldest intact book, St. Cuthbert Gospel (Britain) from the 700s, is purchased for 5.7 million dollars"},
    "0418": {"1906":"Earthquake and fires kill 4,000 and leave 75% of San Francisco buildings destroyed. Estimated 7.9 on the Richter Scale", "1924":"First crossword book published by Americans Simon and Schuster", "1975":"John Lennon gives last public performance in New York City"},
    "0419": {"1775":"Shot heard round the world. The American Revolution starts against Britain", "1943":"Swiss Dr. Albert Hofmann discovers the psychodelic properties of LSD 5 years after he created it", "1982":"Sally Ride named first American woman astronaut. Two cosmonaut women went to space before her"},
    "0420": {"1912":"Famous Boston Red Sox field, Fenway Park, opens", "1971":"Not actually on April 20th, but 5 high school students meet at 4:20pm to find canabis crops in California. Origin of 420", "2021":"Police officer who killed George Floyd convicted for murder. Case caused racial injustice protests all over the country"},
    "0421": {"1820":"Danish physicist Hans Christian Orsted identifies electromagnetism by running electricity through a wire and noticing a compass needle moves", "1956":"Elvis Presley's first hit record, Heartbreak Hotel becomes number 1", "1989":"George W. Bush becomes CEO of the Texas Rangers 3 months after his father becomes President of the US"},
    "0422": {"1500":"Pedro Alvares Cabral is the first European to discover Brazil. Claims it for Portugal", "1914":"Babe Ruth's first major league game. Pitches a shutout for the Baltimore Orioles, beating the Buffalo Bisons 6-0", "1976":"Barbara Walters becomes the first female nightly news anchor in the US on ABC News"},
    "0423": {"1961":"Judy Garland records her Grammy winning album Judy at Carnegie Hall", "1988":"First Federal US ban on smoking in airplanes. Banned on all domestic flights 2-hours or shorter", "2009":"Gamma Ray Burst 090423 is observed for 10 seconds. Travelled 30 billion light years and is the oldest known object in the universe"},
    "0424": {"1895":"Joshua Slocum leaves from Boston aboard a 11.2-m sloop on his first-ever solo circumnavigation of the world", "1958":"Winston Churchill knighted by Queen Elizabeth II", "2005":"Coronation day for Joseph Ratzinger, taking the name Pope Benedict XVI. Becomes the 265th Pope."},
    "0425": {"1898":"US declares war on Spain. Ended by the end of the year, lead by Colonel Teddy Roosevelt", "1954":"First Solar Battery announced. Created by Bell Labs", "1983":"American 11-year old Samantha Smith writes to USSR leader Yuri Andropov. To everyone's surprise, he personally writes back and she visits for 2 weeks"},
    "0426": {"1941":"Ray Nelson starts a tradition by playing the first organ at a baseball stadium. Played at Wrigley Field in Chicago", "1986":"Chernobyl Disaster. The world's worst nuclear disaster explodes from Kiev, USSR and contamination spreads throughout Europe", "2015":"Nursultan Nazarbayev gets record 97.7% of the vote for President of Kazakhstan. 95.2% of eligible voters voted"},
    "0427": {"1810":"Ludvig van Beethoven composes Fur Elise. Was not published until 40 years after his death", "1959":"Mao Zedong retires as President of China after failing his Great Leap Forward program to industrialize Chinese food production. Remained in high political power until his death", "2018":"Presidents of North and South Korea, Kim Jong-un and Moon Jae-in, meet to end the Korean war and denuclearize both countries. Results inconclusive"},
    "0428": {"1817":"After the War of XXXX year, the US and Canada (Britain) sign the Rush-Bagot Treaty, making the US-Canada border the largest demilitarized border in the world", "1965":"USA invades Dominican Republic during their civil war to prevent a communist ruling party", "1987":"NBA announces four new teams: Charlotte Hornets, Miami Heat, Minneapolis Timberwolves, and Orlando Magic"},
    "0429": {"1936":"First pro baseball game in Japan. Nagoya beats Daitokyo 8-5", "1993":"Rodney King riots begin after 4 Los Angeles police officers are acquitted after killing Rodney King", "2015":"German Measles aka Rubella completely eradicated in North and South America"},
    "0430": {"1803":"James Madison signs the Louisiana Purchase Treaty for $15 million. Doubles the size of the USA", "1945":"USSR raises flag over Reichtag in Berlin, symbolizing the fall of Nazi Germany", "1975":"End of US involvement in the Vietname War. North forces conquored the South"},
    "0501": {"1840":"World's first adhesive postage stamp called Penny Black, made by the UK. Depicts Queen Victoria", "1924":"German manufacturers Daimler-Motoren-Gesellschaft and Benz start working together. Later becomes Mercedes-Benz", "1988":"Michael Jordan becomes the first NBA player to score 50+ points in back to back playoff games. Against the Cleveland Cavaliers"},
    "0502": {"":"", " ":"", "  ":""},
    "0503": {"":"", " ":"", "  ":""},
    "0504": {"":"", " ":"", "  ":""},
    "0505": {"":"", " ":"", "  ":""},
    "0506": {"":"", " ":"", "  ":""},
    "0507": {"":"", " ":"", "  ":""},
    "0508": {"":"", " ":"", "  ":""},
    "0509": {"":"", " ":"", "  ":""},
    "0510": {"":"", " ":"", "  ":""},
    "0511": {"":"", " ":"", "  ":""},
    "0512": {"":"", " ":"", "  ":""},
    "0513": {"":"", " ":"", "  ":""},
    "0514": {"":"", " ":"", "  ":""},
    "0515": {"1940":"First McDonalds opens from the McDonalds brothers in San Bernardino, California", " ":"", "2015":"First Martian Marathon. Mars rover Opportunity completed a marathon in 11 hours"},
    "0516": {"":"", " ":"", "  ":""},
    "0517": {"":"", " ":"", "  ":""},
    "0518": {"":"", " ":"", "  ":""},
    "0519": {"":"", " ":"", "  ":""},
    "0520": {"":"", " ":"", "  ":""},
    "0521": {"":"", " ":"", "  ":""},
    "0522": {"":"", " ":"", "  ":""},
    "0523": {"":"", " ":"", "  ":""},
    "0524": {"":"", " ":"", "  ":""},
    "0525": {"":"", " ":"", "  ":""},
    "0526": {"":"", " ":"", "  ":""},
    "0527": {"":"", " ":"", "  ":""},
    "0528": {"":"", " ":"", "  ":""},
    "0529": {"":"", " ":"", "  ":""},
    "0530": {"":"", " ":"", "  ":""},
    "0531": {"":"", " ":"", "  ":""},
    "0601": {"":"", " ":"", "  ":""},
    "0602": {"":"", " ":"", "  ":""},
    "0603": {"":"", " ":"", "  ":""},
    "0604": {"":"", " ":"", "  ":""},
    "0605": {"":"", " ":"", "  ":""},
    "0606": {"":"", " ":"", "  ":""},
    "0607": {"":"", " ":"", "  ":""},
    "0608": {"":"", " ":"", "  ":""},
    "0609": {"":"", " ":"", "  ":""},
    "0610": {"":"", " ":"", "  ":""},
    "0611": {"":"", " ":"", "  ":""},
    "0612": {"":"", " ":"", "  ":""},
    "0613": {"":"", " ":"", "  ":""},
    "0614": {"":"", " ":"", "  ":""},
    "0615": {"":"", " ":"", "  ":""},
    "0616": {"":"", " ":"", "  ":""},
    "0617": {"":"", " ":"", "  ":""},
    "0618": {"":"", " ":"", "  ":""},
    "0619": {"":"", " ":"", "  ":""},
    "0620": {"":"", " ":"", "  ":""},
    "0621": {"":"", " ":"", "1982":"John Hinckley Jr. is found not guilty for shooting President Ronald Reagan under plea of insanity"},
    "0622": {"":"", " ":"", "  ":""},
    "0623": {"":"", " ":"", "  ":""},
    "0624": {"":"", " ":"", "  ":""},
    "0625": {"":"", " ":"", "  ":""},
    "0626": {"":"", " ":"", "  ":""},
    "0627": {"":"", " ":"", "  ":""},
    "0628": {"":"", " ":"", "  ":""},
    "0629": {"":"", " ":"", "  ":""},
    "0630": {"":"", " ":"", "  ":""},
    "0701": {"":"", " ":"", "  ":""},
    "0702": {"":"", " ":"", "  ":""},
    "0703": {"":"", " ":"", "  ":""},
    "0704": {"":"", " ":"", "  ":""},
    "0705": {"":"", " ":"", "  ":""},
    "0706": {"":"", " ":"", "  ":""},
    "0707": {"":"", " ":"", "  ":""},
    "0708": {"":"", " ":"", "  ":""},
    "0709": {"":"", " ":"", "  ":""},
    "0710": {"":"", " ":"", "  ":""},
    "0711": {"":"", " ":"", "  ":""},
    "0712": {"":"", " ":"", "  ":""},
    "0713": {"":"", " ":"", "  ":""},
    "0714": {"":"", " ":"", "  ":""},
    "0715": {"":"", " ":"", "  ":""},
    "0716": {"":"", " ":"", "  ":""},
    "0717": {"":"", " ":"", "  ":""},
    "0718": {"":"", " ":"", "  ":""},
    "0719": {"":"", " ":"", "  ":""},
    "0720": {"":"", " ":"", "  ":""},
    "0721": {"":"", " ":"", "  ":""},
    "0722": {"":"", " ":"", "  ":""},
    "0723": {"":"", " ":"", "  ":""},
    "0724": {"":"", " ":"", "  ":""},
    "0725": {"":"", " ":"", "  ":""},
    "0726": {"":"", " ":"", "  ":""},
    "0727": {"":"", " ":"", "  ":""},
    "0728": {"":"", " ":"", "  ":""},
    "0729": {"":"", " ":"", "  ":""},
    "0730": {"":"", " ":"", "  ":""},
    "0731": {"":"", " ":"", "  ":""},
    "0801": {"":"", " ":"", "  ":""},
    "0802": {"":"", " ":"", "  ":""},
    "0803": {"":"", " ":"", "  ":""},
    "0804": {"":"", " ":"", "  ":""},
    "0805": {"":"", " ":"", "  ":""},
    "0806": {"":"", " ":"", "  ":""},
    "0807": {"":"", " ":"", "  ":""},
    "0808": {"":"", " ":"", "  ":""},
    "0809": {"":"", " ":"", "  ":""},
    "0810": {"":"", " ":"", "  ":""},
    "0811": {"":"", " ":"", "  ":""},
    "0812": {"":"", " ":"", "  ":""},
    "0813": {"":"", " ":"", "  ":""},
    "0814": {"":"", " ":"", "  ":""},
    "0815": {"":"", " ":"", "  ":""},
    "0816": {"":"", " ":"", "  ":""},
    "0817": {"":"", " ":"", "  ":""},
    "0818": {"":"", " ":"", "  ":""},
    "0819": {"":"", " ":"", "  ":""},
    "0820": {"":"", " ":"", "  ":""},
    "0821": {"":"", " ":"", "  ":""},
    "0822": {"":"", " ":"", "  ":""},
    "0823": {"":"", " ":"", "  ":""},
    "0824": {"":"", " ":"", "  ":""},
    "0825": {"":"", " ":"", "  ":""},
    "0826": {"":"", " ":"", "  ":""},
    "0827": {"":"", " ":"", "  ":""},
    "0828": {"":"", " ":"", "  ":""},
    "0829": {"":"", " ":"", "  ":""},
    "0830": {"":"", " ":"", "  ":""},
    "0831": {"":"", " ":"", "  ":""},
    "0901": {"":"", " ":"", "  ":""},
    "0902": {"":"", " ":"", "  ":""},
    "0903": {"":"", " ":"", "  ":""},
    "0904": {"":"", " ":"", "  ":""},
    "0905": {"":"", " ":"", "  ":""},
    "0906": {"":"", " ":"", "  ":""},
    "0907": {"":"", " ":"", "  ":""},
    "0908": {"":"", " ":"", "  ":""},
    "0909": {"":"", " ":"", "  ":""},
    "0910": {"":"", " ":"", "  ":""},
    "0911": {"":"", " ":"", "  ":""},
    "0912": {"":"", " ":"", "  ":""},
    "0913": {"":"", " ":"", "  ":""},
    "0914": {"":"", " ":"", "  ":""},
    "0915": {"":"", " ":"", "  ":""},
    "0916": {"":"", " ":"", "  ":""},
    "0917": {"":"", " ":"", "  ":""},
    "0918": {"1851":"New York Times. posts its first newspaper. Yes the name had the period", " ":"", "  ":""},
    "0919": {"":"", " ":"", "  ":""},
    "0920": {"":"", " ":"", "  ":""},
    "0921": {"":"", " ":"", "  ":""},
    "0922": {"":"", " ":"", "  ":""},
    "0923": {"":"", " ":"", "  ":""},
    "0924": {"":"", " ":"", "  ":""},
    "0925": {"":"", " ":"", "  ":""},
    "0926": {"":"", " ":"", "  ":""},
    "0927": {"":"", " ":"", "  ":""},
    "0928": {"":"", " ":"", "  ":""},
    "0929": {"":"", " ":"", "  ":""},
    "0930": {"":"", " ":"", "  ":""},
    "1001": {"1661": "Yachting begins in England", "1800": "Spain cedes Louisiana to France in a secret treaty", "1961": "Roger Maris breaks Babe Ruth's record with his 61st home run", "1975": "Muhammad Ali beats Joe Frazier in the Thrilla in Manilla"},
    "1002": {"1627": "Chongzhen becomes the last emperor of the Chinese Ming Dynasty", "1871": "Brigham Young, US Mormon leader, arrested for bigamy", "1967": "Thurgood Marshall is sworn in as the first black Supreme Court Justice"},
    "1003": {"1888": "New Zealand plays rugby in the UK and becomes the first national team to wear all black and perform the haka", "1971": "Billie Jean King becomes the first female athlete to win $100,000 in prize money in one year", "1995": "OJ Simpson found not guilty"},
    "1004": {"1883":"First Orient Express Train departs from Paris to Istanbul", "1895":"First US Open golf tournament played in Rhode Island", "1957":"Sputnik I becomes the first man-made satellite into elliptical low orbit"},
    "1005": {"1789":"Women march on Versailles during the French Revolution", "1947":"Harry Truman first televised president from the White House", "2020":"At least 14M tons of plastic pieces are at the bottom of the ocean, 30 times more than on the surface according to research"},
    "1006": {"1889":"Moulin Rouge opens in Paris", "1951":"Stalin proclaims the USSR has the atomic bomb", "2021":"World's first Malaria vaccine recommended for widespread use by the WHO"},
    "1007": {"1763":"King George III in the Proclamation of this year declares white settlement cannot pass the Alleghenies, upsetting colonists", "1959":"Far side of the moon seen for the first time in USSR's Luna 3", "1993":"Toni Morrison receives the Nobel Prize for Literature"},
    "1008": {"1840":"First Hawaiian constitution proclaimed by King Kamehameha III and Kuhina Nui Kekauluohi", "1871":"Great Chicago Fire kills 300, leaves 100,000+ homeless, and burns the original Emancipation Proclamation", "2004":"Wangari Maathai of Kenya is the first African woman to win the Nobel Peace Prize"},
    "1009": {"768":"Charlemagne and brother Carloman I are coronated as the kings of France", "1965":"Beatles hit Yesterday hits #1 and stays there for 4 weeks", "2012":"Malala Yousafzai shot 3 times by Taliban trying to go to school in Pakistan"},
    "1010": {"1861":"Fridtjof Nansen, Arctic Explorer, neuroscientist, Nobel Peace Prize winner (and my idol) was born" ,"1913":"Yuan Shikai becomes the 1st president of China", "2005":"Angela Merkel Becomes prime minister of Germany"},
    "1011": {"1945":"Chinese Civil war begins between Kuomintang government and Mao Zedong's Communist Party", "1949":"Costa Rica becomes first country to abolish their army with Decree 249", "1992":"First three-way US presidential debate between George H.W. Bush, Bill Clinton, and Ross Perot"},
    "1012": {"1492":"Christopher Columbus hits where he believes is East Asia but is likely Waiting Island, Bahamas", "1931":"Christ the Redeemer statue is opened in Rio de Janeiro standing 30 m (98 ft) high", "2019":"Eliud Kipchoge from Kenya becomes the first person to run a marathon in under 2 hours! (1:59:40) in Vienna"},
    "1013": {"1903":"First baseball world series Boston Americans beat the Pittsburgh Pirates in Game 8, winning the series 5-3", "1924":"Mecca becomes part of Saudi Territory by military intervention lead by Abdulaziz Ibn Saud", "1987":"First military use of trained dolphins for the US Navy in the Persian Gulf"},
    "1014": {"1834":"First African-American, Henry Blair, granted a US patent for a corn planter", "1964":"Martin Luther King Jr. wins the Nobel Peace Prize", "2007":"Keeping up with the Kardashians premiers"},
    "1015": {"1522":"Hernan Cortes, Spanish Conquistador of the Aztecs, becomes governor of Mexico", "1967":"The Motherland Calls is completed in Volgograd, Russia, at the time the tallest statue 57 m (171 ft)", "1993":"Nelson Mandela and F.W. de Klerk win the Nobel Peace Prize"},
    "1016": {"1813":"The biggest battle before WWI, Napoleon is defeated by Prussia, Austria, and Russia", "1946":"10 Nazi leaders hanged in the Nuremberg Trials", "2004":"Lionel Messi, 17-years old, makes his league debut for FC Barcelona"},
    "1017": {"1904":"Bank of America (originally Bank of Italy) opened in San Fransisco", "1931":"Al Capone convicted on 5 accounts of tax evasion. Sentenced to 11 years in jail", "1979":"Mother Teresa wins the Nobel Peace Prize"},
    "1018": {"1867":"The US purchases Alaska from Russia for $7.2 million. Today's equivalent of about 40 cents per acre", "1921":"Charles Strite granted US patent for the automatic pop-up toaster", "1974":"Nate Thurmond of the Chicago Bulls sets the first Quadruple Double: 22 points, 14 rebounds, 13 assists, and 12 blocks"},
    "1019": {"1722":"The automatic fire extinguisher is patented in England by French C. Hopffer","1781":"General Cornwallis surrenders to George Washington, ending the US Revolutionary War", "1986":"Allan Border scores the 1,000,000th run recorded in test cricket (started in 1877)"},
    "1020": {"1924":"First Negro Leagues World Series. KC Monarchs beat Hilldales 5-0", "1973":"Sydney Opera House opens", "2022":"UK Prime Minister Liz Truss has the shortest term in UK history by resigning after only 44 days"},
    "1021": {"1520":"Ferdinand Magellan reach Cape Virgenes becoming the first Europeans to sail to the Pacific", "1923":"The first true planetarium (with a projector) opens in the Deutsche Museum in Munich", "1945":"Women in France can vote for the first time"},
    "1022": {"1836":"Sam Houston becomes the 1st President of the Republic of Texas", "1953":"Laos gains full independence from France", "1981":"US national debt surpasses $1 trillion"},
    "1023": {"1896":"American football coach John Heisman (namesake of the College Football Trophy) was born", "1958":"Smurfs debut on television", "2018":"World's longest sea-crossing bridge, the Hong Kong-Macau-Zhuhai bridge, opened (55km, 34mi)"},
    "1024": {"79":"Mt. Vesuvius erupts burying 4 cities and killing thousands", "1930":"A Brazilian coup d'etat replaces the last President of the First Republic, Washington Luis Pereira de Sousa, with Getulio Vargas", "1962":"Soviet ships during the Cuban Missile Crisis approach the US blockade of Cuba"},
    "1025": {"1780":"John Hancock becomes the first Governor of Massachusetts", "1983":"United States invades Grenada to overthrow communist regime. Lasted 4 days", "1995":"Cliff Richard becomes the first rock star to be knighted by Queen Elizabeth II"},
    "1026": {"1949":"President Harry Truman increases United States minimum wage from 40 to 75 cents", "1972":"First instant camera, the Polaroid SX-70 is unveiled by Edwin Land","2017":"Jacinda Ardern sworn in as New Zealand Prime Minister. She was the youngest ever female head of state at 37 years old"},
    "1027": {"1787":"First Federalist Papers published in New York newspapers under pseudonym Publius", "1858":"Theodore 'Teddy' Roosevelt, US President, was born", "2017":"Catalan's parliament unanimously declares independence from Spain. Denied by Spanish government"},
    "1028": {"1858":"The first Macy's department store opens in New York City", "1886":"Statue of Liberty dedicated by President Grover Cleveland in New York City", "1919":"Volstead Act passed in US Congress, establishing prohibition"},
    "1029": {"1929":"Wall Street crashes, starting the Great Depression", "1987":"Thomas Hearns becomes the first to win a boxing title in 4 different weight classes", "2015":"China ends their one-child policy after 35 years"},
    "1030": {"1873":"The 'Greatest Show on Earth' circus by P.T. Barnum debuts", "1868":"John Menard from Louisiana becomes the first African American elected to US Congress", "1973":"Turkey finishes the Bosphorus Bridge in Istanbul, connecting Europe and Asia over the river for the first time"},
    "1031": {"1517":"Martin Luther sends his 95 Theses to the Catholic Church, beginning the Protestant Reformation", "1984":"Indian Prime Minister Indira Gandhi is assassinated and her son, Rajiv Gandhi takes office in her place", "2018":"World's biggest statue, the Statue of Unity, is unveiled in Gujarat, India, standing at 182 m (587 ft)"},
    "1101": {"1512":"Sistine Chapel in Vatican City reveals Michelangelo's paintings", "1922":"Republic of Turkey proclaimed by Mustafa Kemal Ataturk, ending the Ottoman Empire", "1993":"12 Countries sign the Maastricht Treaty, the founding of the European Union"},
    "1102": {"1898":"Johnny Cambell starts cheerleading in the US. An all-male team cheers on the University of Minnesota", "1963":"South Vietnam president, Ngo Dinh Diem is overthrown in a coup by the army", "1983":"Ronald Regan establishes Dr. Martin Luther King Jr. as a federal holiday"},
    "1103": {"1783":"George Washington disbands the Continental Army (they did that)", "1957":"Laika, a Siberian husky, becomes the first animal in space, launched by the USSR", "2014":"NYC One World Trade Center, 1776 ft (541m) tall, opens to commemorate the twin towers"},
    "1104": {"1841":"First American settlers travel 5 months and get to California", "1897":"African American inventor Thomas Elkins patents the Refrigerating Apparatus", "1979":"500 Iranian students take over the US Embassy in Tehran, taking 90 hostages"},
    "1105": {"1905":"Roald Amundsen completes finds the first 'Northwest Passage' (from the Atlantic to the Pacific above Canada) after 400 years of attempts", "1916":"German and Austro-Hungarian Emporers establish the Kingdom of Poland", "2007":"China's satellite, Chane'e 1, is the first of theirs to orbit the moon"},
    "1106": {"1860":"Abraham Lincoln elected 16th president of the United States", "1917":"Bolshevik Revolution begins with bombing of Winter Palace in Petrograd", "1991":"Russian President Boris Yeltsin outlaws the communist party"},
    "1107": {"1800":"Women wearing trousers in Paris becomes illegal (officially unbanned in 2013)", "1805":"Lewis and Clark first reach the Pacific Ocean", "1874":"Thomas Nast makes the first political cartoon depicting the Republican Party as an elephant"},
    "1108": {"1731":"Benjamin Franklin opens the first library in the North American colonies in Philadelphia", "1895":"German Wilhelm Rontgen becomes the first to produce and detect X-rays", "2005":"Ellen Johnson-Sirleaf becomes the first female leader of an African country, elected president of Liberia"},
    "1109": {"1620":"The Mayflower spots land in what is now the United States at Cape Cod", "1906":"Theodore Roosevelt becomes first US President to visit another country while in office -- Puerto Rico and Panama", "2015":"San Diego SeaWorld ends its killer whale show after controversy over the whale's treatment"},
    "1110": {"1885":"Gottlieb Damler releases the worlds first motorcycle in Germany", "1954":"Marine Corps War Memorial unvelied. Dedicated to the US Marines. Based on the 1945 Iwo Jima raising the US Flag", "1989":"Berlin Wall starts to get taken down"},
    "1111": {"1675":"German Gottfried Wilhelm Leibniz presents integral calculus for the first time", "1918":"The 11th hour of the 11th day of the 11th month WWI Armistice is signed, ending the war", "1933":"First of the Dust Bowl storms, the 'Great Black Blizzard' goes through South Dakota"},
    "1112": {"1927":"Leon Trotsky kicked out of the Soviet Communist Party, leading to Joseph Stalin having complete power", "1966":"Buzz Aldrin takes the first space selfie doing extravehicular activity with the Earth in the background", "1990":"The World Wide Web first proposed by CERN scientists Tim Berners-Lee and Robert Cailliau"},
    "1113": {"1856":"Big Ben's Great Bell chimes for first time outside the almost finished clock tower", "1927":"The Holland Tunnel connecting New York City to New Jersey under the Hudson River opens and is the first twin-tube underwater auto tunnel", "1956":"US Supreme Court rules race separation on buses unconstitutional"},
    "1114": {"1888":"USC Trojans (then the Methodists) play their first football game", "1994":"First public trains run through the English Channel connecting England and France", "2018":"UK Cabinet approves draft plan for Brexit, the UK's exit from the EU"},
    "1115": {"1811":"Jose Miguel Carrera becomes the first Chilean President after a coup", "1939":"FDR places the cornerstone for the Jefferson Memorial in DC", "2021":"Joe Biden signs a $1 trillion infrastructure bill"},
    "1116": {"1581":"Tsar Ivan the Terrible attacks his son and heir, leading to his death three days later", "1922":"Monarchy abolished ending the Ottoman Empire", "1938":"Swiss Chemist, Dr. Albert Hofmann, synthesized LSD, a hallucinogenic drug, for the first time"},
    "1117": {"1800":"US Congress holds the first session in Washington, D.C. in an unfinished Capitol Building", "1970":"The patent for the patent for the first computer mouse is granted to Douglas Engelbart", "2008":"Twilight premieres in Los Angeles"},
    "1118": {"326":"Old St. Peter's Basilica is consecrated in Rome (present-day Vatican City)", "1626":"St. Peter's Basilica is consecrated on the same site and is the world's largest Christian basilica", "1978":"918 members of the 'People's Temple' are murdered or commit suicide under Jim Jones leadership in Jonestown, Guyana"},
    "1119": {"1863":"Abraham Lincoln delivers the Gettysburg Address in Pennsylvania after one of the bloodiest battles in the American Civil War", "1965":"Kellogg releases the Pop Tart pastry", "2006":"Wii is released in North America by Nintendo"},
    "1120": {"1969":"Brazillian football player Pele scores his 1000th goal", "1982":"Drew Barrymore hosts Saturday Night Live while she's 7 years old", "2018":"Amitabh Bachchan, an Indian actor, paid off the debts of 1398 farmers during an Indian agricultural crisis"},
    "1121": {"1976":"Hit movie Rocky starting Sylvester Stallone premieres in New York", "1989":"Smoking cigarettes banned on all US domestic flights", "2017":"Robert Mugabe of Zimbabwe resigns after 37 years in power"},
    "1122": {"1497":"Vasco de Gama of Portugal goes around the Cape of Good Hope in Africa, the first European ocean voyage to India", "1963":"US President John F. Kennedy assassinated in Dallas, Texas", "1986":"Mike Tyson becomes the youngest heavyweight boxing champion at 20 years old after defeating Trevor Berbick"},
    "1123": {"1889":"First Jukebox debuted in San Francisco", "1921":"US President Warren Harding signs 'Anti-Beer Bill' preventing doctors from prescribing beer or liquor", "2011":"During the Arab Spring, Yemeni President Ali Abdullah Saleh transfers power to the VP after 11 months of protests"},
    "1124": {"1859":"Charles Darwin publishes 'On the Origin of Species' laying the foundation for evolutionary biology", "1954":"First US Presidential airplane, Air Force One, is christened", "2012":"Gangnam style becomes the most viewed Youtube video, passing 808 million views"},
    "1125": {"1975":"The Netherlands grants independence to Suriname", "1990":"Lech Walesa wins Poland's first popular election", "2019":"Louis Vuitton buys Tiffany & Co. for more than $16 billion"},
    "1126": {"1825":"Oldest continuous fraternity, Kappa Alpha, founded in Union College, NY", "1922":"English archeologist Howard Carter opens Pharoh Tutankhamun's (King Tut) mostly intact tomb in Egypt ", "1965":"First French satellite named Asterix launched"},
    "1127": {"1807":"Escaping Napoleon, the Portuguese Royal Family and 15,000 royals leave Lisbon for Brazil", "1895":"Alfred Nobel's will (at death) establishes the Nobel Peace Prize", "1999":"Helen Clark becomes the first female Prime Minister of New Zealand in the Labour Party"},
    "1128": {"1717":"Pirate Blackbeard captures a French ship renamed as Queen Anne's Revenge", "1895":"First auto race in the US. 6 cars, 55 miles. Winner Frank Duryea averages 7 miles per hour", "2021":"Honduras' Xiomara Castro elected first female president"},
    "1129": {"1877":"Thomas Edison demonstrates hand-cranked phonograph (record player) for the first time", "1947":"UN votes to allow the partition of Palestine between Arabs and Jews", "1972":"First commercially successful video game, Pong, released by Nolan Bushnell in Sunnyvale, California"},
    "1130": {"1838":"Mexico declares war on France during the Pastry Wars", "1967":"Yemen declares independence from the UK", "1982":"Thriller, album by Michael Jackson, released. Becomes the best-selling album of all time (and still is)"},
    "1201": {"1821":"Dominican Republic declares independence from Spain", "1913":"The first moving assembly line is instituted by Ford for their Model T", "1990":"English and French tunnel diggers meet in the middle of the first tunnel to cross the English Channel"},
    "1202": {"1804":"Napolean is crowned Emperor of France", "1957":"First US nuclear powerplant for peaceful use opens in Shippingport, Pennsylvania", "1971":"United Arab Emirates declares independence from the United Kingdom"},
    "1203": {"1854":"Seen as the start to Australian democracy, the Eureka Stockade gold miner uprising lead to governance change", "1967":"First human heart transplant performed in South Africa by Dr. Christiaan Barnard", "1989":"USSR President Mikhail Gorbachev and US President George H.W. Bush declare the Cold War is over"},
    "1204": {"1619":"Considered by many to be the first Thanksgiving, 38 colonists in Virginia give thanks to God", "1954":"First Burger King opens", "2018":"First birth from a uterus transplant from deceased donor in Sao Paulo, Brazil"},
    "1205": {"1360":"The French Franc (currency until the Euro in 2002) was created", "1848":"US President James K. Polk starts the gold rush after confirming gold found in California", "1955":"Bus Boycott, led by Rosa Parks and other civil rights activists, begins in Montgomery, Alabama"},
    "1206": {"1240":"Mongols under leader Batu Khan destroy Kyiv (modern-day Ukraine)", "1921":"Anglo-Irish Treaty creates Northern Ireland and gives the rest of Ireland dominion status", "1956":"While the USSR invades Hungary militarily, in the Melbourne Olympics, Hungary defeats the USSR in water polo"},
    "1207": {"1909":"Leo Baekeland of New York patents thermo-setting plastic called Bakelite. This is the birth of the plastics industry", "1941":"Japanese suicide bombers kill thousands at Pearl Harbor, destroying a large percentage of the American navy", "2020":"Coca Cola is the world's number 1 plastic pollute: 200,000 tons or about 8 billion bottles per year."},
    "1208": {"1966":"US and USSR sign treaty to ban nuclear weapons in outer space", "1980":"Annie Leibovitz has a photo shoot with Jon Lennon, and he is murdered later that day", "2010":"SpaceX becomes the first private company to launch, orbit, and recover a spacecraft"},
    "1209": {"1868":"First traffic lights installed in London. Illuminated at night by red and green gas lamps", "1935":"First Heisman Trophy goes to Jay Berwanger of Chicago", "1990":"Lech Walesa wins Poland's 1st direct presidential election in Poland"},
    "1210": {"1869":"Wyoming becomes first US municipality (territory at the time) to grant women's suffrage", "1898":"Treaty of Paris ends the Spanish-American War. US acquires Philippines, Puerto Rico, and Guam", "1984":"First planet discovered outside of the solar system"},
    "1211": {"1946":"UNICEF (United Nations International Children's Emergency Fund) established", "1994":"Russia invades Grozny, beginning the first Chechen War. Chechen Republic gains independence and loses it less than 5 years later", "2014":"World's first penis transplant in Cape Town, South Africa"},
    "1212": {"1874":"Hawaiian King David Kalakaua is the first king to visit the US. He is a guest of President Ulysses S. Grant", "1901":"Guglielmo Marconi sends first transatlantic radio signal from Cornwall, England to Newfoundland, Canada", "1991":"Nigeria makes Abuja the capital, replacing Lagos. Abuja is the present-day capital"},
    "1213": {"1642":"First European sighting of New Zealand by Dutch Abel Tasman. He originally called it Staten Landt and changed it a year later to Nieuw Zeeland", "1983":"Highest scoring NBA game. Detroit beats Denver 186-184 in triple overtime", "2001":"Five terrorists attack Indian Parliament. They kill ten and all 5 attackers were killed"},
    "1214": {"1542":"Princess Mary Stuart succeeds her father James V and becomes Queen Mary I of Scotland at 6 days old", "1911":"Norwegian Roald Amundsen's expedition is the first to reach the South Pole", "1995":"The Dayton Agreement is signed by Bosnian, Croatian, Serbian, and US Presidents, ending violence between these regions of Yugoslavia... kind of"},
    "1215": {"1791":"The US Bill of Rights ratified after Virginia becomes the 10th out of 14 states. These are the first 10 amendments to the US Constitution", "1832":"Gustave Eiffel, architect and engineer of the Eiffel Tower, born in Dijon, France", "2011":"Leaning Tower of Pisa reopens after 11 years and 27 million dollars to fortify, without fixing the lean"},
    "1216": {"1773":"Boston Tea Party. Protesters of British taxes throw tea in the Boston Harbor", "1950":"Shirley Temple retires from films at age 22", "1971":"East Pakistan celebrates Victory Day for breaking off with Pakistan and becoming an independent Bangladesh"},
    "1217": {"1903":"Wright Brothers perform the first plane flight in Kitty Hawk, North Carolina", "1924":"First Diesel-Electric locomotive in service in Bronx, New York", "1959":"American film On The Beach is the first to premier on both sides of the Iron Curtain"},
    "1218": {"1271":"The Yuan Dynasty starts in China after Kublai Khan renames the empire", "1603":"First Dutch East India Company fleet departs for, you guessed it, the East Indies", "2009":"Highest grossing movie of all time, Avatar, released"},
    "1219": {"1958":"First radio broadcast from space. Eisenhower says to all mankind, America's wish for peace on Earth and goodwill everywhere", "1984":"Chinese and British leaders sign a Joint Declaration to transfer Hong Kong back to China 13 years later", "2012":"Park Geun-hye becomes the first female president of South Korea"},
    "1220": {"1812":"Grimm's Fairy Tales by Brothers Grimm published with stories Rapunzel, Hansel and Gretel, and Snow White", "1924":"Hitler released from prison 4 years early from sentence. Wrote Mein Kampf while incarcerated", "1977":"First spacewalk by Soviet cosmonaut Georgy Grechko"},
    "1221": {"1891":"First basketball game invented by James Naismith played in Massachusetts", "1913":"First crossword puzzle printed in NY World", "1956":"Bus Boycott ends with Supreme Court ruling segregated busses unconstitutional"},
    "1222": {"1882":"First Christmas tree lights made by Thomas Edison", "1990":"Iraq proclaims it will never give up Kuwait. Kuwait is liberated 2 months later", "2016":"First Ebola vaccine found to be 70-100% effective"},
    "1223": {"1888":"Vincent Van Gogh cuts his own left ear off", "1954":"First successful human kidney transplant by Dr. Joseph Murray in Boston, Massachusetts", "1997":"Hanukkah candle lit in Vatican City for the first time"},
    "1224": {"1814":"Treaty of Ghent ends war of 1812 between the USA and the UK", "1956":"I Love Lucy Christmas Special airs","1989":"First Liberian Civil War starts when Charles Taylor leads guerilla group to overthrow current President"},
    "1225": {"336":"First recorded date of Christmas being celebrated on Dec. 25. Celebrated under Roman Emperor Constantine I", "1656":"Dutch Christiaan Huygens invents first pendulum clock", "1741":"Centigrade temperature scale proposed by Swede Anders Celsius"},
    "1226": {"1933":"Patent granted to American Edwin Howard Armstrong for FM Radio", "1946":"Flamingo hotel opens in Las Vegas","1982":"Time's Person of the Year is the Computer"},
    "1227": {"1932":"Radio City Hall (where I work) opened up in Rockefeller Center, New York", "1945":"World Bank created with 28 nations signing agreement", "2007":"Previous Pakistani Prime Minister Benazir Bhutto assassinated by suicide bomber"},
    "1228": {"1612":"First observation of Neptune by Galileo. He noticed it was a fixed star without realizing", "1860":"Harriet Tubman finishes her last mission after 8 years on the Underground Railroad. Ends in Auburn, NY", "2012":"Vladamir Putin bans US adoption of Russian Children"},
    "1229": {"1835":"US government signs Treaty of New Echota cedes all lands of Cherokee east of the Mississippi to the US", "1911":"Sun Yat-Sen elected 1st president of the Republic of China", "1952":"First hearing aid with transistors, allowing creation of a much smaller device"},
    "1230": {"1922":"USSR formally created in Moscow with Russia, Ukraine, Belarus, Armenia, Azerbaijan, and Georgia", "1953":"First color television on sale in US for $1,175. It had a 15-inch screen","1974":"Beatles Paul McCartney lawsuit officially disbanded the band"},
    "1231": {"1907":"First ball drop for New Years in Times Square, New York ", "1911":"Marie Curie wins second Nobel Prize in Chemistry for discovering elements polonium and radium", "2014":"First free election in Tunisia. Beji Caid Essebsi elected president"}
}