var today_in_history = {
    "0101": {"":"", " ": "", "2023": "Tom Brady breaks the NFL record as the oldest player to have a 400+ yard passing game at 45 years and 151 days"},
    "0102": {"":"", " ": "", " ":""},
    "0103": {"":"", " ": "", " ":""},
    "0104": {"":"", " ": "", " ":""},
    "0105": {"":"", " ": "", " ":""},
    "0106": {"":"", " ": "", " ":""},
    "0107": {"":"", " ": "", " ":""},
    "0108": {"":"", " ": "", " ":""},
    "0109": {"":"", " ": "", " ":""},
    "0110": {"":"", " ": "", " ":""},
    "0111": {"":"", " ": "", " ":""},
    "0112": {"":"", " ": "", " ":""},
    "0113": {"":"", " ": "", " ":""},
    "0114": {"":"", " ": "", "2024": "Agnes Ngetich sets the women's 10,000m record with a time of 29:01.03"},
    "0115": {"":"", " ": "", " ":""},
    "0116": {"":"", " ": "", " ":""},
    "0117": {"":"", " ": "", " ":""},
    "0118": {"":"", " ": "", " ":""},
    "0119": {"":"", " ": "", " ":""},
    "0120": {"":"", " ": "", " ":""},
    "0121": {"":"", " ": "", " ":""},
    "0122": {"":"", " ": "", " ":""},
    "0123": {"":"", " ": "", "2015":"Klay Thompson scores the most points in one quarter, 37"},
    "0124": {"":"", " ": "", " ":""},
    "0125": {"":"", " ": "", " ":""},
    "0126": {"":"", " ": "", " ":""},
    "0127": {"":"", " ": "", " ":""},
    "0128": {"":"", " ": "", " ":""},
    "0129": {"":"", " ": "", " ":""},
    "0130": {"":"", " ": "", " ":""},
    "0131": {"1920": "Joe Malone breaks the NHL record most goals in a regular season game with 7", " ": "", " ":""},
    "0201": {"":"", " ": "", " ":""},
    "0202": {"":"", " ": "", " ":""},
    "0203": {"":"", " ": "", " ":""},
    "0204": {"":"", " ": "", " ":""},
    "0205": {"":"", " ": "", " ":""},
    "0206": {"":"", " ": "", " ":""},
    "0207": {"":"", " ": "", " ":""},
    "0208": {"":"", " ": "", " ":""},
    "0209": {"":"", " ": "", " ":""},
    "0210": {"":"", " ": "", " ":""},
    "0211": {"":"", " ": "", " ":""},
    "0212": {"":"", " ": "", " ":""},
    "0213": {"":"", " ": "", " ":""},
    "0214": {"":"", " ": "", " ":""},
    "0215": {"":"", " ": "", " ":""},
    "0216": {"":"", " ": "", " ":""},
    "0217": {"":"", " ": "", " ":""},
    "0218": {"":"", " ": "", " ":""},
    "0219": {"":"", " ": "", " ":""},
    "0220": {"":"", " ": "", " ":""},
    "0221": {"":"", " ": "", " ":""},
    "0222": {"1981": "Peter Stastny and Anton Stastny break the NHL record most points in a road game with 8", " ": "", " ":""},
    "0223": {"":"", " ": "", " ":""},
    "0224": {"":"", " ": "", " ":""},
    "0225": {"":"", " ": "", " ":""},
    "0226": {"":"", " ": "", " ":""},
    "0227": {"":"", " ": "", " ":""},
    "0228": {"":"", " ": "", " ":""},
    "0229": {"":"", " ": "", " ":""},
    "0301": {"":"", " ": "", " ":""},
    "0302": {"":"", " ": "", " ":""},
    "0303": {"":"", " ": "", " ":""},
    "0304": {"":"", " ": "", " ":""},
    "0305": {"":"", " ": "", " ":""},
    "0306": {"":"", " ": "", " ":""},
    "0307": {"":"", " ": "", " ":""},
    "0308": {"":"", " ": "", " ":""},
    "0309": {"":"", " ": "", " ":""},
    "0310": {"":"", " ": "", " ":""},
    "0311": {"":"", " ": "", " ":""},
    "0312": {
        "2011": "Yohann Diniz sets 50,000 m walk (track) world record with a time of 3:35:27.20 in Reims, France",
        " ":"",
        "  ":""
    },
    "0313": {"":"", " ": "", " ":""},
    "0314": {"":"", " ": "", " ":""},
    "0315": {
        "2015": "Yusuke Suzuki sets 20 km walk (road) world record with a time of 1:16:36 at the Asian Race Walking Championships in Nomi, Japan",
        " ":"",
        "  ":""
    },
    "0316": {"":"", " ": "", " ":""},
    "0317": {"":"", " ": "", " ":""},
    "0318": {"":"", " ": "", " ":""},
    "0319": {"":"", " ": "", " ":""},
    "0320": {"":"", " ": "", "2022": "Yulimar Rojas sets the women's triple jump record with a jump of 15.74m"},
    "0321": {"":"", " ": "", " ":""},
    "0322": {"":"", " ": "", " ":""},
    "0323": {"":"", " ": "", " ":""},
    "0324": {"":"", " ": "", " ":""},
    "0325": {"":"", " ": "", " ":""},
    "0326": {"":"", " ": "", " ":""},
    "0327": {"":"", " ": "", " ":""},
    "0328": {"":"", " ": "", " ":""},
    "0329": {"":"", " ": "", " ":""},
    "0330": {"":"", " ": "", " ":""},
    "0331": {"":"", " ": "", " ":""},
    "0401": {"":"", " ": "", " ":""},
    "0402": {"":"", " ": "", " ":""},
    "0403": {"":"", " ": "", " ":""},
    "0404": {"":"", " ": "", " ":""},
    "0405": {"":"", " ": "", " ":""},
    "0406": {"":"", " ": "", " ":""},
    "0407": {"":"", " ": "", " ":""},
    "0408": {"1993": "Carlos Baerga is the first in the MLB to hit home runs from both sides of the plate in the same inning", " ": "", " ":""},
    "0409": {"1987": "Wayne Gretzky most recently ties the NHL record most assists in a playoff game with 6", " ": "", " ":""},
    "0410": {"":"", " ": "", " ":""},
    "0411": {"":"", " ": "", " ":""},
    "0412": {"":"", " ": "", " ":""},
    "0413": {"":"", "1985": "Tim Kerr breaks the NHL record most goals in a playoff period with 4", "2021": "Desiree Linden sets the women's 50km road record with a time of 2:59:54"},
    "0414": {"":"", " ": "", " ":""},
    "0415": {"":"", " ": "", " ":""},
    "0416": {"":"", " ": "", " ":""},
    "0417": {"":"", " ": "", " ":""},
    "0418": {"":"", " ": "", " ":""},
    "0419": {"":"", " ": "", " ":""},
    "0420": {"":"", " ": "", " ":""},
    "0421": {"":"", " ": "", " ":""},
    "0422": {"":"", " ": "", " ":""},
    "0423": {"1999": "Fernando Tatís is the only MLB players to hit 2 grand slams in an inning", " ": "", " ":""},
    "0424": {"":"", " ": "", " ":""},
    "0425": {"1989": "Mario Lemieux breaks the NHL record most goals in a playoff game with 5", " ": "", " ":""},
    "0426": {"":"", " ": "", " ":""},
    "0427": {"":"", " ": "", " ":""},
    "0428": {"":"", " ": "", " ":""},
    "0429": {"1986":"Roger Clemens (Red Sox) becomes the first to strike out 20 batters in one game", " ": "", " ":""},
    "0430": {"":"", " ": "", " ":""},
    "0501": {"":"", "2004": "Barry Bonds breaks the MLB record with 4 intentional walks in a nine-inning game", 
        " ":""},
    "0502": {"":"", " ": "", " ":""},
    "0503": {
        "2015": "Kyle Merber, Brycen Spratling, Brandon Johnson, and Ben Blankenship set distance medley relay world record with a time of 9:15.50 at the World Relays in Nassau, Bahamas",
        " ":"",
        "  ":""
    },
    "0504": {"":"", " ": "", " ":""},
    "0505": {"":"", " ": "", " ":""},
    "0506": {"":"", " ": "", " ":""},
    "0507": {
        "1994": "Bernardo Segura sets 20,000 m walk (track) world record with a time of 1:17:25.6 in Bergen, Norway",
        " ":"",
        "  ":""
    },
    "0508": {"":"", " ": "", " ":""},
    "0509": {"":"", " ": "", " ":""},
    "0510": {"":"", " ": "", " ":""},
    "0511": {"":"", " ": "", "2016": "Max Scherzer breaks the MLB record with 20 strikeouts in a nine-inning game"},
    "0512": {"":"", " ": "", " ":""},
    "0513": {"":"", " ": "", " ":""},
    "0514": {"":"", " ": "", " ":""},
    "0515": {"":"", " ": "", " ":""},
    "0516": {"":"", "2012": "Jamie Moyer breaks the MLB record as the oldest pitcher to win a game at 49 years and 151 days", " ":""},
    "0517": {"":"", " ": "", " ":""},
    "0518": {"1912": "Allan Travers breaks the MLB record allowing 26 hits in a game", " ": "", " ":""},
    "0519": {"":"", " ": "", " ":""},
    "0520": {"":"", " ": "", " ":""},
    "0521": {"":"", " ": "", " ":""},
    "0522": {"":"", " ": "", " ":""},
    "0523": {"":"", "2002": "Shawn Green breaks the MLB record with 19 total bases in a game (4 home runs, double, single)", 
        " ":""},
    "0524": {
        "2014": "Nickel Ashmeade, Warren Weir, Jermaine Brown, and Yohan Blake set 4 x 200 m relay world record with a time of 1:18.63 at the World Relays in Nassau, Bahamas",
        " ":"",
        "  ":""
    },
    "0525": {
        "1996": "Jan Železný sets javelin throw world record with a distance of 98.48 m in Jena, Germany",
        "2014": "Collins Cheboi, Silas Kiplagat, James Kiplagat Magut, and Asbel Kiprop set 4 x 1500 m relay world record with a time of 14:22.22 at the World Relays in Nassau, Bahamas",
        "2024": "Beatrice Chebet sets the women's 10km road record with a time of 28:46"
    },
    "0526": {"":"", " ": "", " ":""},
    "0527": {"":"", " ": "", " ":""},
    "0528": {"":"", " ": "", " ":""},
    "0529": {"":"", " ": "", " ":""},
    "0530": {"":"", " ": "", " ":""},
    "0531": {"":"", " ": "", " ":""},
    "0601": {"":"", " ": "", " ":""},
    "0602": {"":"", " ": "", " ":""},
    "0603": {"":"", " ": "", " ":""},
    "0604": {"":"", " ": "", " ":""},
    "0605": {"":"", " ": "", " ":""},
    "0606": {"1996": "Peter Forsberg breaks the NHL record most goals in one period during the Stanley Cup Finals with 3", " ": "", " ":""},
    "0607": {"1987": "Natalya Lisovskaya sets the women's shot put record with a throw of 22.63m", " ": "", " ":""},
    "0608": {"":"", " ": "", "2021": "Letesenbet Gidey sets the women's 10,000m record with a time of 28:54.14"},
    "0609": {"":"", " ": "", "2019": "Craig Stammen most recently ties the MLB record allowing 4 consecutive home runs in a game"},
    "0610": {"":"", " ": "", " ":""},
    "0611": {"1988": "Galina Chistyakova sets the women's long jump record with a jump of 7.52m", " ": "", " ":""},
    "0612": {"":"", "2010": "Daniel Nava is the most recent MLB player to hit a grand slam on their first career pitch", 
        " ":""},
    "0613": {"":"", " ": "", " ":""},
    "0614": {"":"", " ": "", " ":""},
    "0615": {"":"", " ": "", " ":""},
    "0616": {"":"", " ": "", " ":""},
    "0617": {"":"", " ": "", " ":""},
    "0618": {"":"", " ": "", " ":""},
    "0619": {"":"", " ": "", " ":""},
    "0620": {"":"", " ": "", " ":""},
    "0621": {"":"", " ": "", " ":""},
    "0622": {"":"", " ": "", " ":""},
    "0623": {"":"", " ": "", " ":""},
    "0624": {"":"", " ": "", "2024": "Sydney McLaughlin-Levrone sets the women's 400m hurdles record with a time of 50.65"},
    "0625": {"":"", " ": "", " ":""},
    "0626": {"":"", " ": "", " ":""},
    "0627": {"":"", " ": "", " ":""},
    "0628": {"":"", " ": "", " ":""},
    "0629": {"":"", " ": "", " ":""},
    "0630": {"":"", " ": "", " ":""},
    "0701": {"":"", " ": "", " ":""},
    "0702": {"":"", " ": "", " ":""},
    "0703": {"":"", " ": "", " ":""},
    "0704": {"":"", " ": "", " ":""},
    "0705": {"":"", " ": "", " ":""},
    "0706": {"":"", " ": "", " ":""},
    "0707": {"":"", " ": "", "2024": "Faith Kipyegon sets the women's 1500m record with a time of 3:49.04"},
    "0708": {"":"", " ": "", " ":""},
    "0709": {"1988": "Gabriele Reinsch sets the women's discus throw record with a throw of 76.80m", " ": "", " ":""},
    "0710": {"":"", " ": "", " ":""},
    "0711": {"":"", " ": "", " ":""},
    "0712": {"":"", " ": "", " ":""},
    "0713": {"":"", " ": "", " ":""},
    "0714": {"":"", " ": "", " ":""},
    "0715": {"":"", " ": "", " ":""},
    "0716": {"1988": "Florence Griffith Joyner sets the women's 100m record with a time of 10.49s", " ": "", " ":""},
    "0717": {"1990": "Minnesota Twins break the MLB record as the only team to execute two triple plays in a game", " ": "", " ":""},
    "0718": {"":"", " ": "", " ":""},
    "0719": {"":"", " ": "", " ":""},
    "0720": {"":"", " ": "", " ":""},
    "0721": {"":"", " ": "", "2023": "Faith Kipyegon sets the women's mile record with a time of 4:07.64"},
    "0722": {"":"", " ": "", " ":""},
    "0723": {"":"", " ": "", " ":""},
    "0724": {"":"", " ": "", "2022": "Tobi Amusan sets the women's 100m hurdles record with a time of 12.12"},
    "0725": {"":"", " ": "", " ":""},
    "0726": {"1983": "Jarmila Kratochvílová sets the women's 800m record with a time of 1:53.28", " ": "", " ":""},
    "0727": {"":"", " ": "", " ":""},
    "0728": {"":"", " ": "", "2024": "Yaroslava Mahuchikh sets the women's high jump record with a jump of 2.10m"},
    "0729": {"":"", "2003": "Bill Mueller breaks the MLB record with 1 grand slam from each side of the plate in the same game", 
        " ":""},
    "0730": {"":"", "2012": "Kendrys Morales most recently ties the MLB record hitting home runs from both sides of the plate in the same inning", 
        " ":""},
    "0731": {"":"", " ": "", " ":""},
    "0801": {"":"", "2012": "USA team sets the women's 4x400m relay record with a time of 3:15.17",
        "2024": "Hobbs Kessler sets road mile world record with a time of 3:56.13 at World Road Running Championships in Riga"
    },
    "0802": {"":"", " ": "", " ":""},
    "0803": {"":"", " ": "", " ":""},
    "0804": {"":"", " ": "", " ":""},
    "0805": {"":"", " ": "",
        "2024": "Armand Duplantis sets 6.25m pole vault world record at the Paris Olympics"
    },
    "0806": {"":"", " ": "", " ":""},
    "0807": {
        "1995": "Jonathan Edwards sets triple jump world record with a distance of 18.29m at Gothenburg",
        " ": "", " ":""
    },
    "0808": {
        "1992": "American basketball's Dream Team wins the gold medal at the Barcelona Olympics",
        " ": "", "2021": "Brock Holt breaks the MLB record for the slowest recorded pitch thrown at 30.4 miles per hour"
    },
    "0809": {"1936":"Jesse Owens wins his 4th gold at the Berlin Olympics in the 4x100m", "2012": "David Rudisha sets 800m world record with a time of 1:40.91 at the London Olympics", " ":""},
    "0810": {"":"", " ": "", " ":""},
    "0811": {
        "2012": "Nesta Carter, Michael Frater, Yohan Blake, and Usain Bolt set 4 x 100 m relay world record with a time of 36.84 s at the London Olympic Games, United Kingdom",
        " ":"",
        "  ":""
    },
    "0812": {"":"", " ": "", " ":""},
    "0813": {"":"", " ": "", " ":""},
    "0814": {"":"",
        "2016": "Wayde van Niekerk sets 400m world record with a time of 43.03s at the Rio Olympics",
        "2020": "Joshua Cheptegei sets 5000m world record with a time of 12:35.36 at Herculis, Monaco"
    },
    "0815": {
        "2014": "Yohann Diniz sets 50 km walk (road) world record with a time of 3:32:33 at the European Championships in Zürich, Switzerland",
        " ":"",
        "  ":""
    },
    "0816": {"":"", " ": "",
        "2009": "Usain Bolt beats the 100m world record with a time of 9.58s"
    },
    "0817": {"":"", " ": "", " ":""},
    "0818": {"":"", " ": "", " ":""},
    "0819": {"":"", " ": "", " ":""},
    "0820": {"":"",
        "2009": "Usain Bolt sets 200m world record with a time of 19.19s at the World Championships in Berlin",
        "2018": "Beatrice Chepkoech sets the women's 3000m steeplechase record with a time of 8:44.32"
    },
    "0821": {"":"", " ": "", " ":""},
    "0822": {
        "1993": "Andrew Valmon, Quincy Watts, Butch Reynolds, and Michael Johnson set 4 x 400 m relay world record with a time of 2:54.29 at the World Championships in Stuttgart, Germany",
        " ":"",
        "  ":""
    },
    "0823": {"":"", 
        "1996": "Svetlana Masterkova sets the women's 1000m record with a time of 2:28.98",
        " ":""},
    "0824": {"":"", " ": "", " ":""},
    "0825": {
        "2006": "Joseph Mutua, William Yiampoy, Ismael Kombich, and Wilfred Bungei set 4 x 800 m relay world record with a time of 7:02.43 at the Memorial Van Damme in Brussels, Belgium",
        " ": "",
        "2024": "Armand Duplantis sets 6.26m pole vault world record in the Paris Olympics"
    },
    "0826": {"1984": "Jack", "1994":"Jack D", "2004": "Damiani"},
    "0827": {"":"", " ": "", " ":""},
    "0828": {"":"", "2009": "Yelena Isinbayeva sets the women's pole vault record with a jump of 5.06m", "2016": "Anita Włodarczyk sets the women's hammer throw record with a throw of 82.98m"},
    "0829": {"":"", " ": "", " ":""},
    "0830": {
        "1986": "Yuriy Sedykh sets hammer throw world record with a distance of 86.74 m at the European Championships in Stuttgart, Germany",
        "1987": "Stefka Kostadinova sets the women's high jump record with a jump of 2.09m", 
        " ":""
    },
    "0831": {"":"", " ": "", " ":""},
    "0901": {
        "1947": "First modern Formula 1 Grand Prix Race in Turin, Italy. Won by Achille Varzi",
        "1974": "Mike Marshall (Dodgers) sets a major league record with his 106th pitching appearance in a season",
        "2001": "Venus Williams wins her second US Open title, defeating Serena Williams"
    },
    "0902": {
        "1984": "American Mary Lou Retton wins the Olympic individual all-around gymnastics gold medal",
        "2006": "Andre Agassi plays his last match at the US Open, losing to Benjamin Becker",
        "2018": "Novak Djokovic wins his 14th Grand Slam title at the US Open, tying Pete Sampras"
    },
    "0903": {
        "2000": "Australian Cathy Freeman lights the Olympic flame at the Sydney Olympics",
        "2006": "Roger Federer wins his third consecutive US Open title",
        "2017": "Sloane Stephens wins her first Grand Slam title at the US Open"
    },
    "0904": {
        "1972": "American Mark Spitz wins his 7th gold medal at the Munich Olympics in the 4x100m medley relay",
        "2016": "Stan Wawrinka wins his third Grand Slam title at the US Open",
        "2018": "Naomi Osaka defeats Serena Williams to win her first US Open title"
    },
    "0905": {
        "1994": "American sprinter Leroy Burrell breaks the 100m world record, running 9.85 seconds",
        "2005": "Roger Federer defeats Andre Agassi in the US Open final for his second title",
        "2009": "Kim Clijsters wins her second US Open title, becoming the first unseeded player to win since 1958"
    },
    "0906": {
        "1986": "Martina Navratilova wins her 3rd US singles title",
        "1994": "Barry Bonds becomes the fourth player in MLB history to record 40 homers and 40 steals in a season",
        "1995": "Cal Ripken Jr. plays in his 2,131st consecutive game, breaking Lou Gehrig's record"
    },
    "0907": {
        "1967": "Billie Jean King wins her first US Open title",
        "2008": "Roger Federer wins his fifth consecutive US Open title",
        "2014": "Serena Williams wins her 18th Grand Slam title at the US Open",
    },
    "0908": {
        "1968": "Arthur Ashe wins the US Open, becoming the first African American man to win the title",
        "1998": "Mark McGwire hits his 62nd home run, breaking long-standing 61 from Roger Marris",
        "2021": "Emma Raducanu wins the US Open, becoming the first qualifier to win a Grand Slam title"
    },
    "0909": {
        "2001": "Lleyton Hewitt of Australia becomes youngest (at the time) #1 male tennis player",
        "2018": "Novak Djokovic wins his 14th Grand Slam title at the US Open, tying Pete Sampras",
        "2021": "Tom Brady (Buccaneers) becomes first player to start 300 regular season NFL games"
    },
    "0910": {
        "1988": "Steffi Graf wins the US Open, completing the Golden Slam (all four Grand Slams and an Olympic gold in the same year)",
        "2005": "Kim Clijsters wins her first Grand Slam title at the US Open",
        "2022": "Carlos Alcaraz wins the US Open, becoming the youngest male to win a Grand Slam since 1990"
    },
    "0911": {
        "1985": "Pete Rose breaks Ty Cobb's all-time hits record with his 4,192nd hit",
        "2001": "Michael Jordan announces his second return to the NBA",
        "2020": "Novak Djokovic disqualified from US Open for hitting a ball out of frustration accidentally hitting a line judge"
    },
    "0912": {
        "1979": "Tracy Austin, 16, becomes the youngest US Open women's champion",
        "2004": "Roger Federer wins his first US Open title",
        "2010": "Rafael Nadal wins his first US Open title, completing the Career Grand Slam"
    },
    "0913": {
        "1991": "Kim Zmeskal is 1st American to win a medal at World Gymnastics Championships. Wins with 39.848 pts",
        "1999": "John Elway of Denver Broncos number retired #7",
        "2020": "Austrian Dominic Thiem wins his first Grand Slam title at the US Open"
    },
    "0914": {
        "1968": "Denny McLain (Tigers) wins his 30th game, the last pitcher to do so in MLB",
        "2019": "Rafael Nadal wins his 19th Grand Slam title at the US Open",
        "2021": "Daniil Medvedev wins his first Grand Slam title at the US Open"
    },
    "0915": {
        "1978": "Muhammad Ali defeats Leon Spinks to win the world heavyweight title for the third time and avenge loss",
        "2002": "Rich Gannon (Raiders) begins his record 6 straight games throwing 300 yards in the NFL",
        "2021": "Simone Biles testifies against Gymnastics Doctor and rapist Larry Nassar"
    },
    "0916": {
        "1924": "Jim Bottomley (Cardinals) sets a record with 12 RBIs in a single game",
        "1995": "Greg Maddux (Braves) sets record 17 straight road game pitching victories",
        "2018": "Land speed cycling record broken in Utah by Denise Mueller-Korenek. Bikes an average of 184mph (296km/h)"
    },
    "0917": {
        "2000": "NFL's Dan Marino (Dolphins) number retired #13",
        "2004": "Barry Bonds (Giants) hits his 700th home run off Jake Peavy",
        "2013": "Marian Hossa of the Chicago Blackhawks plays his 1,000th NHL game"
    },
    "0918": {
        "1994": "First Presidents Cup Golf US beats the International team 20-12",
        "1999": "Serena Williams wins her first Grand Slam title at the US Open",
        "2017": "English footballer Wayne Rooney pleads guilty to drunk driving and cannot drive for 2 years"
    },
    "0919": {
        "2004": "Jerry Rice ends his NFL record of 274 consecutive games with a reception",
        "2011": "Mariano Rivera sets record for 602nd career save with the Yankees",
        "2015": "Baker Mayfield sets an Oklahoma football record with 572 total yards: 487 passing, 85 rushing"
    },
    "0920": {
        "1931": "Lou Gehrig broke his own single-season RBI record with 175 RBIs",
        "1987": "Walter Payton broke Jim Brown's rushing TD record with his 107th touchdown",
        "1998": "Cal Ripken Jr.'s streak of 2,632 consecutive games played ended",
    },
    "0921": {
        "1970": "Monday Night Football debuted on ABC, with the Cleveland Browns defeating the New York Jets 31-21",
        "1982": "The first NFL strike began, leading to a shortened season and a new playoff format",
        "2001": "10 days after 9/11, Mets beat the Braves 3-2 with Mike Piazza's iconic 8th-inning HR"
    },
    "0922": {
        "1911": "Cy Young recorded his 511th and final Major League victory, a record that still stands",
        "1969": "Willie Mays hit his 600th career home run, becoming the second player ever to reach the milestone",
        "1990": "Andre Dawson joined Willie Mays as the only players with 2,000 hits, 300 home runs, and 300 stolen bases",
    },
    "0923": {
        "1979": "Lou Brock broke Billy Hamilton's all-time stolen base record with his 938th steal",
        "1988": "Jose Canseco became the first player in MLB history to record 40 home runs and 40 stolen bases in a season",
        "2001": "Patriots QB Drew Bledsoe suffered a devastating injury, and backup Tom Brady starts his long career"
    },
    "0924": {"1961": "Charlie McNeil breaks the NFL record for most interception return yards in a game with 177", 
        "2010": "Aroldis Chapman breaks the MLB record for the fastest recorded pitch thrown at 105.1 miles per hour", 
        "2023": "Jason Sanders ties the NFL record most kicks (PAT) attempted in a game with 10"},
    "0925": {
        "2000": "Vince Carter performed his iconic 'Dunk of Death' over 7'2 Frederic Weis during the Olympic Group Stage against France",
        "2001": "Michael Jordan announced his second return to the NBA, this time with the Washington Wizards",
        "2005": "Buccaneers RB Carnell 'Cadillac' Williams set two rookie records with a 158-yard rushing game, the first player to start a career with three consecutive 100-yard rushing games",
    },
    "0926": {"1965": "Colts RB Lenny Moore's record streak of 18 consecutive games with a TD ended", "2011": "Tony Romo ties NFL record most fumbles recovered in a game with 4", "2021": "Justin Tucker ties the record for longest field goal with 66 yards"},
    "0927": {"1973": "Nolan Ryan set a new MLB record with his 383rd strikeout of the season", 
        "2005": "Braves clinched the NL East title for a U.S. sports record 14th consecutive season",
        "2018": "Jared Goff breaks the NFL record for most passing yards in a perfect passer rating (158.3) game with 465 yards"},
    "0928": {"1941": "Ted Williams became the last player in MLB history to hit over .400",
        "1988": "Orel Hershiser's 59 consecutive scoreless IP set a new MLB record",
        "2019": "Pete Alonsos 53rd HR set a new single-season rookie home run record"},
    "0929": {
        "1977": "Pele plays his final game for the New York Cosmos in an exhibition against Santos",
        "1986": "Greg and Mike Maddux became the 1st pair of brothers to pitch against each other",
        "1988": "Florence Griffith Joyner sets the women's 200m record with a time of 21.34s"},
    "0930": {
        "1927": "Babe Ruth became the 1st in MLB history to hit 60 home runs in a season",
        "1973": "Johnny Unitas became the 1st NFL player to accumulate 40,000 career passing yards",
        "1995": "Albert Belle became the 1st player in history with 50 HR and 50 doubles in a season"
    },
    "1001": {
        "1903": "The Pittsburgh Pirates and Boston Americans played the 1st 'World Series' game ever. Boston Americans won 5-3",
        "1932": "Babe Ruth made his legendary 'called shot' during the World Series",
        "2023": "Diribe Welteji sets the women's road mile record with a time of 4:20.98"
    },
    "1002": {
        "1920": "The last triple-header in MLB history took place between the Reds and Pirates",
        "1950": "TE Bob Shaw set a single-game NFL record with 5 TD receptions",
        "1968": "Bob Gibson sets a World Series record with 17 strikeouts in a single game",
        },
    "1003": {
        "1974": "Frank Robinson became the first black manager in MLB history (Cleveland Indians)",
        "1989": "Art Shell became the first black head coach in modern NFL history (Los Angeles Raiders)",
        "1992": "Maurizio Damilano sets 2 hours walk (track) world record with a distance of 29,572 m and 30,000 m walk (track) world record with a time of 2:01:44.1 in Cuneo, Italy",
    },
    "1004": {
        "1955": "Brooklyn Dodgers won their first World Series in franchise history",
        "1959": "The World Series was played out west for the first time ever as the LA Dodgers won their first WS",
        "2019": "Twins' playoff losing streak expanded to 18, becoming the longest streak in all major U.S. sports leagues"
    },
    "1005": {
        "2001": "Barry Bonds hit his 71st and 72nd HRs, breaking Mark McGwire's single-season home run record",
        "2003": "Dante Hall set an NFL record with a return TD in his 4th consecutive game, which was also the game-winner",
        "2004": "Scottie Pippen announced his retirement after a farewell season with the Chicago Bulls"
    },
    "1006": {"1985": "Marita Koch sets the women's 400m record with a time of 47.60s", 
        "1996":"Tiger Woods wins first PGA Tour event, the Las Vegas Invitational", 
        "2001": "Seattle Mariners won their 116th game, tying the all-time MLB single-season wins record"
    },
    "1007": {"1945": "Don Hutson breaks the NFL record for most touchdowns in one quarter with 4", "1984": "Walter Payton broke Jim Brown's all-time record of 12,312 career rushing yards", "1995": "Edgar Martinez hit a go-ahead grand slam and drove in a postseason-record 7 runs in ALDS Game 4"},
    "1008": {
        "1956": "Don Larsen threw the 1st and only perfect game in MLB World Series history",
        "1995": "Dan Marino passed Fran Tarkenton to become the NFL's career leader in pass completions with 3,686",
        "2018": "Drew Brees broke Peyton Manning's all-time record of 71,940 career passing yards"
    },
    "1009": {
        "1966": "The Orioles threw a World Series record 33 consecutive scoreless innings for a sweep of the Dodgers",
        "1977": "Eddie Brown breaks the NFL record for most punt returns in a game with 11",
        "2019": "Cardinals scored the most runs ever in the 1st inning of a postseason game with 10"
    },
    "1010": {
        "1920": "Elmer Smith hit the 1st grand slam in World Series history",
        "2011": "Nelson Cruz hit the 1st walk-off grand slam in MLB postseason history",
        "2019": "Tom Brady passed Peyton Manning for 2nd place on the all-time passing yards list"
    },
    "1011": { 
        "1992": "Deion Sanders played in an NFL game for the Atlanta Falcons then made it to Pittsburgh for the NLCS with the Braves",
        "1980": "Dallas Mavericks won their NBA debut against the San Antonio Spurs",
        "1998": "Leo Araguz breaks the NFL record for most punting yards by punter in a game with 709"
    },
    "1012": {
        "1979": "Larry Bird and Earvin 'Magic' Johnson both made their NBA debuts for the Celtics and Lakers",
        "1982": "Paul Molitor (Milwaukee Brewers) set a World Series record with 5 hits in a game",
        "1992": "Art Monk made his 820th career reception, breaking the all-time NFL record"
    },
    "1013": {
        "1967": "The American Basketball Association (ABA) officially began play",
        "1985": "Phil Simms and the NY Giants set single-game NFL records in Pass Attempts (62) and 1st downs (34)",
        "2001": "Derek Jeter's iconic 'flip' helped the Yankees defeat the A's in Game 3 of the ALDS"
    },
    "1014": {
        "1906": "The Chicago White Sox defeated the Chicago Cubs in the 1st all-Chicago World Series (4-2)",
        "1990": "Joe Montana threw for 476 yards and 6 TDs, with Jerry Rice becoming the 1st WR with 5 REC TD",
        "2015": "Jose Bautista's iconic bat flip followed a go-ahead HR in the 7th inning of ALDS Game 5"
    },
    "1015": {
        "1966": "Bill Russell (Boston Celtics) became the 1st African-American Head Coach in North American professional sports history",
        "1995": "The Carolina Panthers won their very first game after an 0-5 start",
        "2019": "The Washington Nationals clinched their 1st World Series and became the 1st team to have SPs K 11+ in 3 straight playoff games"
    },
    "1016": {
        "1964": "Yankees fire manager Yogi Berra one day after losing the World Series",
        "1985": "Kansas City Royals won their 1st World Series by defeating the St. Louis Cardinals in Game 7",
        "2004": "Boston Red Sox completed a historic comeback to win the ALCS against the New York Yankees, down 0-3 and winning 4-3"},
    "1017": {
        "1943": "Detroit Lions recorded a record -53 rushing yards in a loss to the Chicago Cardinals",
        "1989": "A major earthquake hit the Bay Area minutes before Game 3 of the World Series, postponing the game for 10 days",
        "2019": "Patrick Mahomes became the quickest in NFL history to reach 7,500 career passing yards"
    },
    "1018": {
        "1974": "Nate Thurmond recorded the first quadruple-double in NBA history with 22 points, 14 rebounds, 13 assists, and 12 blocks",
        "1977": "Reggie Jackson hit 3 home runs in Game 6 of the World Series, leading the New York Yankees to their 21st title and earning the nickname 'Mr. October'",
        "2009": "Tom Brady threw a record five touchdown passes in a single quarter during a 59-0 win over the Tennessee Titans"
    },
    "1019": {"1960": "Oscar Robertson and Jerry West make their NBA debuts against each other", 
        "2004": "Curt Schilling pitches a bloody sock game for the Red Sox vs the Yankees, forcing a Game 7 in the ALCS",
        "2008": "Tampa Bay Rays defeat the Boston Red Sox in Game 7 of the ALCS to advance to their first World Series", 
        },
    "1020": {"2002": "Shannon Sharpe breaks the NFL record for most receiving yards in a game by a tight end with 214",
        "2004": "Red Sox eliminate the Yankees in Game 7, completing the first 3-0 postseason comeback in MLB history", 
        "2015": "Adam Vinatieri ties the record most consecutive field goals made with 44"},
    "1021": {"1980": "Philadelphia Phillies win their first World Series title over the Kansas City Royals", "1998": "New York Yankees set the all-time record for wins in a calendar year (125)", "2007": "Rob Bironas breaks the NFL record most field goals made in a game with 8"},
    "1022": {"1939": "The first televised professional football game was broadcasted on NBC. Brooklyn Dodgers play the Philadelphia Eagles", "2000": "Corey Dillon of the Cincinnati Bengals breaks Walter Payton's single-game rushing record with 278 yards", "2017": "JuJu Smith-Schuster breaks the NFL record as the youngest player to have a touchdown reception since 1930 at 20 years and 334 days"},
    "1023": {"1993": "Joe Carter hits his iconic walk-off home run to win back-to-back World Series for the Blue Jays", "1994": "Robert Bailey breaks the NFL record for longest punt return with 103 yards", "2019":"Justin Verlander becomes the 1st pitcher to reach 200 career postseason strikeouts"},
    "1024": {"1959": "Wilt Chamberlain makes his NBA debut with the Philadelphia Warriors, scoring 43 points and grabbing 28 rebounds", "2010": "DeAngelo Hall breaks the NFL record for most interceptions in one half with 4", "2021": "Letesenbet Gidey sets the women's half marathon record with a time of 1:05:16"},
    "1025": {"1964": "Jim Marshall mistakenly returns a fumble 66 yards the wrong way, resulting in a safety for the 49ers", "1986": "Mets win World Series Game 6 after a ground ball goes through Red Sox 1B Bill Buckner's legs, extending the series", "1998": "Jerry Rice sets an NFL record with 184 consecutive games with a catch and becomes the first player to surpass 17,000 career receiving yards"},
    "1026": {"1975": "Billie Jean King defeats Bobby Riggs in the 'Battle of the Sexes' tennis match (Suggested by \u2615 Supporter)", "2005": "Chicago White Sox ended an 87-year championship drought by winning the World Series against the Houston Astros",
        "2018": "Los Angeles Dodgers won the longest World Series game ever, with Max Muncy hitting a walk-off home run in the 18th inning"},
    "1027": {"2002": "Anaheim Angels won their first World Series, defeating the San Francisco Giants 4-1 in Game 7", 
        "2004": "Boston Red Sox ended the 'Curse of the Bambino,' sweeping the St. Louis Cardinals to win their first World Series since 1918", 
        "2019": "Bill Belichick became the third NFL head coach to win 300 games, defeating the Cleveland Browns"},
    "1028": {"1989": "The Oakland Athletics swept the San Francisco Giants to win the World Series after a 10-day delay caused by an earthquake",
        "1997": "Violet Palmer and Dee Kantner became the first female referees in the NBA and in any male professional sport", "2012": "Jason Witten breaks the NFL record for most pass receptions in one half with 13"},
    "1029": {"1995": "Jerry Rice surpassed James Lofton to become the NFL's all-time leader in receiving yards, finishing the game with 108 yards",
        "2003": "LeBron James made his NBA debut, scoring 25 points, nine assists, and four rebounds for the Cleveland Cavaliers in a loss to the Sacramento Kings",
        "2018": "Klay Thompson set an NBA record with 14 three-pointers in a single game, surpassing Steph Curry's previous record (Suggested by \u2615 Supporter)"},
    "1030": {"1954": "The NBA implemented the 24-second shot clock, revolutionizing the pace of the game by preventing teams from stalling possessions",
        "1981": "Hall of Fame PG Isiah Thomas made his NBA debut for the Detroit Pistons, scoring 31 points and dishing out 11 assists in a victory over the Milwaukee Bucks",
        "2019": "The Washington Nationals won their first-ever World Series title, defeating the Houston Astros in Game 7, making it the only World Series where the road team won every game"},
    "1031": {"1950": "Earl Lloyd became the first African-American player to play in an NBA game, breaking the color barrier in the league",
        "2004": "The Pittsburgh Steelers, led by rookie QB Ben Roethlisberger, snapped the New England Patriots' NFL-record 21-game winning streak",
        "2018": "Derrick Rose scored a career-high 50 points for the Minnesota Timberwolves, marking a triumphant performance seven years after his MVP season and multiple career-threatening injuries"},
    "1101": {"1946": "The Basketball Association of America (BAA), which later merged into the NBA, officially began play with a game between the New York Knicks and Toronto Huskies",
        "2001": "Derek Jeter hit a walk-off home run just after midnight in Game 4 of the World Series, earning the nickname 'Mr. November.'",
        "2017": "The Houston Astros won their first-ever World Series by defeating the Los Angeles Dodgers in a seven-game series"},
    "1102": {"1990": "The Golden State Warriors and Denver Nuggets combined for 320 points in a non-overtime NBA game, the highest-scoring regulation game in league history",
        "2005": "Andrew Bynum made his NBA debut for the Los Angeles Lakers at 18 years and 6 days old, becoming the youngest player in league history",
        "2016": "The Chicago Cubs won their first World Series in 108 years, defeating the Cleveland Indians 8-7 in a thrilling Game 7 that went to extra innings"},
    "1103": {"1934": "Lou Gehrig won the American League Triple Crown with a .363 batting average, 49 home runs, and 166 RBI, but did not win the AL MVP",
        "1996": "Jerry Rice became the first NFL player to record 1,000 career receptions in a game against the Carolina Panthers", 
        "2019": "Austin Seibert ties the record most field goals made in one quarter with 4"},
    "1104": {"1973": "The Chicago Bears allowed an NFL-record -12 passing yards to the Green Bay Packers in a 31-17 victory",
        "2001": "The Arizona Diamondbacks defeated the New York Yankees on a walk-off hit by Luis Gonzalez in Game 7 to win their first World Series", 
        "2007": "Adrian Peterson breaks the NFL record for most yards gained in a game with 296",
        },
    "1105": {"2008": "Greg Maddux won his 18th and final Gold Glove award, setting a major league record for both pitchers and overall MLB players",  "2000": "Aeneas Williams ties NFL record longest fumble return with 104 yards", "2023": "C. J. Stroud breaks the NFL record for most passing yards in a game by a rookie with 470"},
    "1106": {"1981": "Fernando Valenzuela became the first rookie to win the NL Cy Young Award, also earning Rookie of the Year honors and helping the Dodgers win the World Series",
        "1984": "The U.S. Supreme Court ruled in favor of the Raiders' move to Los Angeles, and the Cleveland Browns announced their move to Baltimore", "1994": "Mark Royals breaks the NFL record for most punts inside the 20 in a game with 8"},
    "1107": {"1963": "Elston Howard became the first African-American player to win the American League MVP award while playing for the New York Yankees",
        "1991": "Magic Johnson announced his HIV diagnosis and retirement from the NBA, becoming one of the first professional athletes to publicly disclose their status",
        "2008": "Jerry Sloan became the first head coach to win 1,000 games with one franchise, achieving this milestone with the Utah Jazz"},
    "1108": {"1959": "Elgin Baylor set a new NBA record with 64 points in a game against the Boston Celtics, along with 17 rebounds, becoming one of two players in NBA history to have multiple 60-point, 15-rebound games",
        "1966": "Frank Robinson became the first and only player in MLB history to win the MVP award in both the National and American Leagues, achieving the feat with the Cincinnati Reds and Baltimore Orioles",
        "1992": "The Sacramento Kings defeated the Los Angeles Lakers for the first time in 44 attempts, ending a 43-game losing streak in LA"},
    "1109": { "1989": "The Milwaukee Bucks defeated the Seattle SuperSonics in the longest game since the shot clock's inception, winning 155-154 after five overtimes",
        "1993": "Micheal Williams with the Timberwolves set an NBA record for consecutive free throws made, ending his streak at 97 in a loss to the Spurs",
        "2007": "Chinese basketball icons Yao Ming and Yi Jianlian faced off for the first time in the NBA, marking a significant moment for fans in China"},
    "1110": {"1990": "The Phoenix Suns set an NBA record by scoring 107 points in the first half of a game against the Denver Nuggets, ultimately winning 173-143",
        "1996": "Dan Marino became the first player in NFL history to reach 50,000 career passing yards and complete 4,000 career passes",
        "1997": "Roger Clemens became the first pitcher to win four AL Cy Young awards, achieving the pitching Triple Crown with the Toronto Blue Jays"},
    "1111": {"1946": "The New York Knicks made their debut in Madison Square Garden, losing 78-68 in overtime to the Chicago Stags",
        "1990": "Derrick Thomas set an NFL record with seven sacks in a single game against the Seattle Seahawks",
        "2014": "Dirk Nowitzki passed Hakeem Olajuwon to become the highest-scoring foreign-born player in NBA history"},
    "1112": {"1892": "William 'Pudge' Heffelfinger became the first professional football player by accepting $500 to play for the Allegheny Athletic Association", "1995": "Dan Marino passed Fran Tarkenton to become the NFL's all-time leader in passing yards at the time with 47,003", 
        "2019": "Mike Fiers revealed the Houston Astros' World Series sign-stealing scandal, leading to suspensions and firings in MLB",},
    "1113": {"1979": "Darryl Dawkins of the Philadelphia 76ers became the first player to shatter a backboard in an NBA game", "1994": "Drew Bledsoe breaks the NFL record for most pass attempts in a game with 70", "2005": "Nathan Vasher of the Chicago Bears returned a missed FG 108 yards for the longest play in NFL history at the time"},
    "1114": {"1993": "Don Shula won his 325th game, becoming the NFL’s all-time leader in coaching victories", "2009": "Brandon Jennings broke the Milwaukee Bucks' rookie record with a 55-point game, the most by a rookie since 1968",
        "2019": "Myles Garrett (Cleveland Browns) infamously removed Mason Rudolph's helmet and used it as a weapon, leading to an indefinite suspension"},
    "1115": {"1961": "Roger Maris (NY Yankees) won AL MVP with just 4 more votes than his teammate Mickey Mantle after a record-breaking 61 HR season",
        "1970": "Paul Brown, as HC of the Bengals, exacted his revenge on the Browns (after firing him) in a 14-10 victory, calling it his 'greatest' victory",
        "2018": "LeBron James dropped 44 points to pass Wilt Chamberlain for 5th on the all-time NBA scoring list"},
    "1116": {"1957": "Bill Russell set an NBA record with 32 rebounds in a single half", "1998": "Roger Clemens became the first pitcher in MLB history to win five Cy Young awards. Eventually wins 7", "2014": "Mike Evans breaks the NFL record as the youngest player to have a 200 yard receiving game at 21 years and 87 days"},
    "1117": {"1953": "The St. Louis Browns relocated to Baltimore and officially became the Orioles",
        "1960": "The Washington Senators relocated to Minnesota to become the Twins, with a new Senators team replacing them in D.C", 
        "1981": "Bill Cartwright tied an NBA record by converting all 19 of his free throws"},
    "1118": {"1949": "Jackie Robinson was named NL MVP just two years after winning the inaugural Rookie of the Year award",
        "1966": "Sandy Koufax, a three-time Cy Young and 1963 MVP award winner, announced his shocking retirement at the age of 30",
        "2019": "Philip Rivers (San Diego Chargers) lost his 61st career one-score game, an NFL record"},
    "1119": {"1961": "Jim Brown sets a single-game rushing record with 242 yards and 4 TDs",
        "2004": "The 'Malice at the Palace' occurs, one of the most violent fights in sports history between the Indiana Pacers and Detroit Pistons (and their fans)",
        "2019": "LeBron James becomes the 1st player ever to record a triple-double against all 30 NBA franchises"},
    "1120": {"1977": "Walter Payton (Chicago Bears) has the original 'Flu Game' against the Vikings, rushing for 275 yards",
        "1997": "AC Green breaks Randy Smith's NBA record for most consecutive games played ending his streak eventually with 1,192 games",
        "2019": "Ben Simmons hits the 1st 3-pointer of his NBA career after starting out 0-17"},
    "1121": {"1956": "Don Newcombe awarded the 1st-ever Cy Young and NL MVP, winning 27 games with a 3.06 ERA",
        "1969": "Bob Cousy makes his coaching debut at 41 with the Cincinnati Royals (basketball) while playing sparingly",
        "1973": "Pete Rose wins MVP for the only time in his career, hitting .338 with 12 first-place votes"},
    "1122": {"1950": "Fort Wayne Pistons and Minneapolis Lakers combine for the lowest-scoring game in NBA history, final score 19-18",
        "1963": "Most sporting events canceled after JFK's assassination, except NFL games, sparking public backlash",
        "1981": "Kellen Winslow (San Diego Chargers) ties NFL record with 5 receiving TDs in a 55-21 victory over the Raiders"},
    "1123": {
        "2005": "Josephat Ndambiri, Martin Mathathi, Daniel Muchunu Mwangi, Mekubo Mogusu, Onesmus Nyerre, and John Kariuki set road relay 42.195 km world record with a time of 1:57:06 at the Chiba Ekiden in Chiba, Japan",
        "2008": "Ed Reed breaks the NFL record for the longest interception return with 108 yards",
        "2014": "Giants rookie WR Odell Beckham Jr. made one of the greatest catches of all-time with one hand in a game against the Cowboys"
    },
    "1124": {"1960": "Philadelphia Warriors C Wilt Chamberlain collected an NBA-record 55 rebounds in a single game against the Boston Celtics.", 
        "1996": "Sam Mills breaks the NFL record as the oldest player to return a fumble for a touchdown at 37 years and 174 days",
        "2001": "Terry Porter became the first player in NBA history to record 15,000 points, 7,000 assists, 1,000 steals, and 1,000 3-pointers.",},
    "1125": {"":"", " ": "", "2020": "Tyler Bass ties the record most field goals made 50+ yards in a half with 3"},
    "1126": {"1989": "Flipper Anderson breaks the NFL record for most receiving yards in a game with 336",
        " ": "", " ":""},
    "1127": {"":"", " ": "", " ":""},
    "1128": {"":"", " ": "", " ":""},
    "1129": {"":"", "2009": "LaDainian Tomlinson breaks the NFL record for most consecutive rushing attempts without a fumble with 1,001",
        "2020": "Jeremy Chinn breaks NFL record most fumble return touchdowns in a game with 2"},
    "1130": {"":"", " ": "", " ":""},
    "1201": {"":"", " ": "", " ":""},
    "1202": {"":"", " ": "", " ":""},
    "1203": {"":"", " ": "", " ":""},
    "1204": {"":"", " ": "", " ":""},
    "1205": {"":"", " ": "", " ":""},
    "1206": {"":"", " ": "", " ":""},
    "1207": {"":"", " ": "", " ":""},
    "1208": {"":"", " ": "", " ":""},
    "1209": {"2001": "Tim Brown breaks the NFL record as the oldest player to return a punt for a touchdown at 35 years and 140 days", " ": "", "2018": "Tremaine Edmunds breaks the NFL record as the youngest player to have an interception at 20 years and 221 days"},
    "1210": {"":"", " ": "", " ":""},
    "1211": {"":"", " ": "", " ":""},
    "1212": {"1999": "Qadry Ismail breaks the NFL record for most receiving yards in one quarter with 210", " ": "", " ":""},
    "1213": {"":"", "2009": "Brandon Marshall breaks the NFL record for most pass receptions in a game with 21", 
        " ":""},
    "1214": {"1974": "George Blanda breaks the NFL record as the oldest player to throw a touchdown pass at 47 years and 88 days", " ": "", " ":""},
    "1215": {"":"", " ": "", " ":""},
    "1216": {"":"", " ": "", " ":""},
    "1217": {"1988": "Jamie Morris breaks the NFL record for most rushing attempts in a game with 45",
        " ": "", " ":""},
    "1218": {"":"", " ": "", " ":""},
    "1219": {"2004": "Jerry Rice breaks the NFL record as the oldest player to have a touchdown reception at 42 years and 67 days", " ": "", " ":""},
    "1220": {"":"", " ": "", " ":""},
    "1221": {"":"", " ": "", " ":""},
    "1222": {"1985": "Stephone Paige breaks the NFL record for most receiving yards in one half with 258", "1996": "Clay Matthews Jr. breaks the NFL record as the oldest player to have a sack at 40 years and 282 days", " ":""},
    "1223": {"":"", "2012": "Jamaal Charles breaks the NFL record for most yards gained in one quarter with 165", " ":""},
    "1224": {"":"", "2000": "Vinny Testaverde breaks the NFL record for most pass attempts in a regulation game with 69",
        "2011": "Eli Manning ties the record for longest pass completion at 99 yards"},
    "1225": {"":"", " ": "", "2020": "Alvin Kamara ties the record for most touchdowns in a game with 6"},
    "1226": {"":"", " ": "", "2020": "Tom Brady breaks the NFL record as the oldest player with a 158.3 perfect passer rating at 43 years, 145 days"},
    "1227": {"1981": "Wayne Gretzky breaks the NHL record fastest 100 points from the start of a season in 34 games", " ": "", "2023": "Kris Letang breaks the NHL record most assists in one period with 5"},
    "1228": {"":"", " ": "", " ":""},
    "1229": {"2002": "Todd Lyght breaks the NFL record as the oldest player to return a blocked field goal for a touchdown at 33 years and 323 days", " ": "", " ":""},
    "1230": {"":"", "2012": "Zach Brown ties the NFL record for most interceptions returned for touchdowns in a game with 2", " ":""},
    "1231": {"":"", " ": "", "2023": "Beatrice Chebet sets the women's 5km road record with a time of 14:13"}
    
    
}