var today_in_history = {
    "0101": {"":"", " ": "", " ":""},
    "0102": {"":"", " ": "", " ":""},
    "0103": {"":"", " ": "", " ":""},
    "0104": {"":"", " ": "", " ":""},
    "0105": {"":"", " ": "", " ":""},
    "0106": {"":"", " ": "", " ":""},
    "0107": {"":"", " ": "", " ":""},
    "0108": {"":"", " ": "", " ":""},
    "0109": {"":"", " ": "", " ":""},
    "0110": {"":"", " ": "", " ":""},
    "0111": {"":"", " ": "", " ":""},
    "0112": {"":"", " ": "", " ":""},
    "0113": {"":"", " ": "", " ":""},
    "0114": {"":"", " ": "", "2024": "Agnes Ngetich sets the women's 10,000m record with a time of 29:01.03"},
    "0115": {"":"", " ": "", " ":""},
    "0116": {"":"", " ": "", " ":""},
    "0117": {"":"", " ": "", " ":""},
    "0118": {"":"", " ": "", " ":""},
    "0119": {"":"", " ": "", " ":""},
    "0120": {"":"", " ": "", " ":""},
    "0121": {"":"", " ": "", " ":""},
    "0122": {"":"", " ": "", " ":""},
    "0123": {"":"", " ": "", " ":""},
    "0124": {"":"", " ": "", " ":""},
    "0125": {"":"", " ": "", " ":""},
    "0126": {"":"", " ": "", " ":""},
    "0127": {"":"", " ": "", " ":""},
    "0128": {"":"", " ": "", " ":""},
    "0129": {"":"", " ": "", " ":""},
    "0130": {"":"", " ": "", " ":""},
    "0131": {"":"", " ": "", " ":""},
    "0201": {"":"", " ": "", " ":""},
    "0202": {"":"", " ": "", " ":""},
    "0203": {"":"", " ": "", " ":""},
    "0204": {"":"", " ": "", " ":""},
    "0205": {"":"", " ": "", " ":""},
    "0206": {"":"", " ": "", " ":""},
    "0207": {"":"", " ": "", " ":""},
    "0208": {"":"", " ": "", " ":""},
    "0209": {"":"", " ": "", " ":""},
    "0210": {"":"", " ": "", " ":""},
    "0211": {"":"", " ": "", " ":""},
    "0212": {"":"", " ": "", " ":""},
    "0213": {"":"", " ": "", " ":""},
    "0214": {"":"", " ": "", " ":""},
    "0215": {"":"", " ": "", " ":""},
    "0216": {"":"", " ": "", " ":""},
    "0217": {"":"", " ": "", " ":""},
    "0218": {"":"", " ": "", " ":""},
    "0219": {"":"", " ": "", " ":""},
    "0220": {"":"", " ": "", " ":""},
    "0221": {"":"", " ": "", " ":""},
    "0222": {"":"", " ": "", " ":""},
    "0223": {"":"", " ": "", " ":""},
    "0224": {"":"", " ": "", " ":""},
    "0225": {"":"", " ": "", " ":""},
    "0226": {"":"", " ": "", " ":""},
    "0227": {"":"", " ": "", " ":""},
    "0228": {"":"", " ": "", " ":""},
    "0229": {"":"", " ": "", " ":""},
    "0301": {"":"", " ": "", " ":""},
    "0302": {"":"", " ": "", " ":""},
    "0303": {"":"", " ": "", " ":""},
    "0304": {"":"", " ": "", " ":""},
    "0305": {"":"", " ": "", " ":""},
    "0306": {"":"", " ": "", " ":""},
    "0307": {"":"", " ": "", " ":""},
    "0308": {"":"", " ": "", " ":""},
    "0309": {"":"", " ": "", " ":""},
    "0310": {"":"", " ": "", " ":""},
    "0311": {"":"", " ": "", " ":""},
    "0312": {
        "2011": "Yohann Diniz sets 50,000 m walk (track) world record with a time of 3:35:27.20 in Reims, France",
        " ":"",
        "  ":""
    },
    "0313": {"":"", " ": "", " ":""},
    "0314": {"":"", " ": "", " ":""},
    "0315": {
        "2015": "Yusuke Suzuki sets 20 km walk (road) world record with a time of 1:16:36 at the Asian Race Walking Championships in Nomi, Japan",
        " ":"",
        "  ":""
    },
    "0316": {"":"", " ": "", " ":""},
    "0317": {"":"", " ": "", " ":""},
    "0318": {"":"", " ": "", " ":""},
    "0319": {"":"", " ": "", " ":""},
    "0320": {"":"", " ": "", "2022": "Yulimar Rojas sets the women's triple jump record with a jump of 15.74m"},
    "0321": {"":"", " ": "", " ":""},
    "0322": {"":"", " ": "", " ":""},
    "0323": {"":"", " ": "", " ":""},
    "0324": {"":"", " ": "", " ":""},
    "0325": {"":"", " ": "", " ":""},
    "0326": {"":"", " ": "", " ":""},
    "0327": {"":"", " ": "", " ":""},
    "0328": {"":"", " ": "", " ":""},
    "0329": {"":"", " ": "", " ":""},
    "0330": {"":"", " ": "", " ":""},
    "0331": {"":"", " ": "", " ":""},
    "0401": {"":"", " ": "", " ":""},
    "0402": {"":"", " ": "", " ":""},
    "0403": {"":"", " ": "", " ":""},
    "0404": {"":"", " ": "", " ":""},
    "0405": {"":"", " ": "", " ":""},
    "0406": {"":"", " ": "", " ":""},
    "0407": {"":"", " ": "", " ":""},
    "0408": {"":"", " ": "", " ":""},
    "0409": {"":"", " ": "", " ":""},
    "0410": {"":"", " ": "", " ":""},
    "0411": {"":"", " ": "", " ":""},
    "0412": {"":"", " ": "", " ":""},
    "0413": {"":"", " ": "", "2021": "Desiree Linden sets the women's 50km road record with a time of 2:59:54"},
    "0414": {"":"", " ": "", " ":""},
    "0415": {"":"", " ": "", " ":""},
    "0416": {"":"", " ": "", " ":""},
    "0417": {"":"", " ": "", " ":""},
    "0418": {"":"", " ": "", " ":""},
    "0419": {"":"", " ": "", " ":""},
    "0420": {"":"", " ": "", " ":""},
    "0421": {"":"", " ": "", " ":""},
    "0422": {"":"", " ": "", " ":""},
    "0423": {"":"", " ": "", " ":""},
    "0424": {"":"", " ": "", " ":""},
    "0425": {"":"", " ": "", " ":""},
    "0426": {"":"", " ": "", " ":""},
    "0427": {"":"", " ": "", " ":""},
    "0428": {"":"", " ": "", " ":""},
    "0429": {"1986":"Roger Clemens (Red Sox) becomes the first to strike out 20 batters in one game", " ": "", " ":""},
    "0430": {"":"", " ": "", " ":""},
    "0501": {"":"", " ": "", " ":""},
    "0502": {"":"", " ": "", " ":""},
    "0503": {
        "2015": "Kyle Merber, Brycen Spratling, Brandon Johnson, and Ben Blankenship set distance medley relay world record with a time of 9:15.50 at the World Relays in Nassau, Bahamas",
        " ":"",
        "  ":""
    },
    "0504": {"":"", " ": "", " ":""},
    "0505": {"":"", " ": "", " ":""},
    "0506": {"":"", " ": "", " ":""},
    "0507": {
        "1994": "Bernardo Segura sets 20,000 m walk (track) world record with a time of 1:17:25.6 in Bergen, Norway",
        " ":"",
        "  ":""
    },
    "0508": {"":"", " ": "", " ":""},
    "0509": {"":"", " ": "", " ":""},
    "0510": {"":"", " ": "", " ":""},
    "0511": {"":"", " ": "", " ":""},
    "0512": {"":"", " ": "", " ":""},
    "0513": {"":"", " ": "", " ":""},
    "0514": {"":"", " ": "", " ":""},
    "0515": {"":"", " ": "", " ":""},
    "0516": {"":"", " ": "", " ":""},
    "0517": {"":"", " ": "", " ":""},
    "0518": {"":"", " ": "", " ":""},
    "0519": {"":"", " ": "", " ":""},
    "0520": {"":"", " ": "", " ":""},
    "0521": {"":"", " ": "", " ":""},
    "0522": {"":"", " ": "", " ":""},
    "0523": {"":"", " ": "", " ":""},
    "0524": {
        "2014": "Nickel Ashmeade, Warren Weir, Jermaine Brown, and Yohan Blake set 4 x 200 m relay world record with a time of 1:18.63 at the World Relays in Nassau, Bahamas",
        " ":"",
        "  ":""
    },
    "0525": {
        "1996": "Jan Železný sets javelin throw world record with a distance of 98.48 m in Jena, Germany",
        "2014": "Collins Cheboi, Silas Kiplagat, James Kiplagat Magut, and Asbel Kiprop set 4 x 1500 m relay world record with a time of 14:22.22 at the World Relays in Nassau, Bahamas",
        "2024": "Beatrice Chebet sets the women's 10km road record with a time of 28:46"
    },
    "0526": {"":"", " ": "", " ":""},
    "0527": {"":"", " ": "", " ":""},
    "0528": {"":"", " ": "", " ":""},
    "0529": {"":"", " ": "", " ":""},
    "0530": {"":"", " ": "", " ":""},
    "0531": {"":"", " ": "", " ":""},
    "0601": {"":"", " ": "", " ":""},
    "0602": {"":"", " ": "", " ":""},
    "0603": {"":"", " ": "", " ":""},
    "0604": {"":"", " ": "", " ":""},
    "0605": {"":"", " ": "", " ":""},
    "0606": {"":"", " ": "", " ":""},
    "0607": {"1987": "Natalya Lisovskaya sets the women's shot put record with a throw of 22.63m", " ": "", " ":""},
    "0608": {"":"", " ": "", "2021": "Letesenbet Gidey sets the women's 10,000m record with a time of 28:54.14"},
    "0609": {"":"", " ": "", " ":""},
    "0610": {"":"", " ": "", " ":""},
    "0611": {"1988": "Galina Chistyakova sets the women's long jump record with a jump of 7.52m", " ": "", " ":""},
    "0612": {"":"", " ": "", " ":""},
    "0613": {"":"", " ": "", " ":""},
    "0614": {"":"", " ": "", " ":""},
    "0615": {"":"", " ": "", " ":""},
    "0616": {"":"", " ": "", " ":""},
    "0617": {"":"", " ": "", " ":""},
    "0618": {"":"", " ": "", " ":""},
    "0619": {"":"", " ": "", " ":""},
    "0620": {"":"", " ": "", " ":""},
    "0621": {"":"", " ": "", " ":""},
    "0622": {"":"", " ": "", " ":""},
    "0623": {"":"", " ": "", " ":""},
    "0624": {"":"", " ": "", "2024": "Sydney McLaughlin-Levrone sets the women's 400m hurdles record with a time of 50.65"},
    "0625": {"":"", " ": "", " ":""},
    "0626": {"":"", " ": "", " ":""},
    "0627": {"":"", " ": "", " ":""},
    "0628": {"":"", " ": "", " ":""},
    "0629": {"":"", " ": "", " ":""},
    "0630": {"":"", " ": "", " ":""},
    "0701": {"":"", " ": "", " ":""},
    "0702": {"":"", " ": "", " ":""},
    "0703": {"":"", " ": "", " ":""},
    "0704": {"":"", " ": "", " ":""},
    "0705": {"":"", " ": "", " ":""},
    "0706": {"":"", " ": "", " ":""},
    "0707": {"":"", " ": "", "2024": "Faith Kipyegon sets the women's 1500m record with a time of 3:49.04"},
    "0708": {"":"", " ": "", " ":""},
    "0709": {"1988": "Gabriele Reinsch sets the women's discus throw record with a throw of 76.80m", " ": "", " ":""},
    "0710": {"":"", " ": "", " ":""},
    "0711": {"":"", " ": "", " ":""},
    "0712": {"":"", " ": "", " ":""},
    "0713": {"":"", " ": "", " ":""},
    "0714": {"":"", " ": "", " ":""},
    "0715": {"":"", " ": "", " ":""},
    "0716": {"1988": "Florence Griffith Joyner sets the women's 100m record with a time of 10.49s", " ": "", " ":""},
    "0717": {"":"", " ": "", " ":""},
    "0718": {"":"", " ": "", " ":""},
    "0719": {"":"", " ": "", " ":""},
    "0720": {"":"", " ": "", " ":""},
    "0721": {"":"", " ": "", "2023": "Faith Kipyegon sets the women's mile record with a time of 4:07.64"},
    "0722": {"":"", " ": "", " ":""},
    "0723": {"":"", " ": "", " ":""},
    "0724": {"":"", " ": "", "2022": "Tobi Amusan sets the women's 100m hurdles record with a time of 12.12"},
    "0725": {"":"", " ": "", " ":""},
    "0726": {"1983": "Jarmila Kratochvílová sets the women's 800m record with a time of 1:53.28", " ": "", " ":""},
    "0727": {"":"", " ": "", " ":""},
    "0728": {"":"", " ": "", "2024": "Yaroslava Mahuchikh sets the women's high jump record with a jump of 2.10m"},
    "0729": {"":"", " ": "", " ":""},
    "0730": {"":"", " ": "", " ":""},
    "0731": {"":"", " ": "", " ":""},
    "0801": {"":"", "2012": "USA team sets the women's 4x400m relay record with a time of 3:15.17",
        "2024": "Hobbs Kessler sets road mile world record with a time of 3:56.13 at World Road Running Championships in Riga"
    },
    "0802": {"":"", " ": "", " ":""},
    "0803": {"":"", " ": "", " ":""},
    "0804": {"":"", " ": "", " ":""},
    "0805": {"":"", " ": "",
        "2024": "Armand Duplantis sets 6.25m pole vault world record at the Paris Olympics"
    },
    "0806": {"":"", " ": "", " ":""},
    "0807": {
        "1995": "Jonathan Edwards sets triple jump world record with a distance of 18.29m at Gothenburg",
        " ": "", " ":""
    },
    "0808": {
        "1992": "American basketball's Dream Team wins the gold medal at the Barcelona Olympics",
        " ": "", " ":""

    },
    "0809": {"1936":"Jesse Owens wins his 4th gold at the Berlin Olympics in the 4x100m", "2012": "David Rudisha sets 800m world record with a time of 1:40.91 at the London Olympics", " ":""},
    "0810": {"":"", " ": "", " ":""},
    "0811": {
        "2012": "Nesta Carter, Michael Frater, Yohan Blake, and Usain Bolt set 4 x 100 m relay world record with a time of 36.84 s at the London Olympic Games, United Kingdom",
        " ":"",
        "  ":""
    },
    "0812": {"":"", " ": "", " ":""},
    "0813": {"":"", " ": "", " ":""},
    "0814": {"":"",
        "2016": "Wayde van Niekerk sets 400m world record with a time of 43.03s at the Rio Olympics",
        "2020": "Joshua Cheptegei sets 5000m world record with a time of 12:35.36 at Herculis, Monaco"
    },
    "0815": {
        "2014": "Yohann Diniz sets 50 km walk (road) world record with a time of 3:32:33 at the European Championships in Zürich, Switzerland",
        " ":"",
        "  ":""
    },
    "0816": {"":"", " ": "",
        "2009": "Usain Bolt beats the 100m world record with a time of 9.58s"
    },
    "0817": {"":"", " ": "", " ":""},
    "0818": {"":"", " ": "", " ":""},
    "0819": {"":"", " ": "", " ":""},
    "0820": {"":"",
        "2009": "Usain Bolt sets 200m world record with a time of 19.19s at the World Championships in Berlin",
        "2018": "Beatrice Chepkoech sets the women's 3000m steeplechase record with a time of 8:44.32"
    },
    "0821": {"":"", " ": "", " ":""},
    "0822": {
        "1993": "Andrew Valmon, Quincy Watts, Butch Reynolds, and Michael Johnson set 4 x 400 m relay world record with a time of 2:54.29 at the World Championships in Stuttgart, Germany",
        " ":"",
        "  ":""
    },
    "0823": {"":"", 
        "1996": "Svetlana Masterkova sets the women's 1000m record with a time of 2:28.98",
        " ":""},
    "0824": {"":"", " ": "", " ":""},
    "0825": {
        "2006": "Joseph Mutua, William Yiampoy, Ismael Kombich, and Wilfred Bungei set 4 x 800 m relay world record with a time of 7:02.43 at the Memorial Van Damme in Brussels, Belgium",
        " ": "",
        "2024": "Armand Duplantis sets 6.26m pole vault world record in the Paris Olympics"
    },
    "0826": {"1984": "Jack", "1994":"Jack D.", "2004": "Damiani"},
    "0827": {"":"", " ": "", " ":""},
    "0828": {"":"", "2009": "Yelena Isinbayeva sets the women's pole vault record with a jump of 5.06m", "2016": "Anita Włodarczyk sets the women's hammer throw record with a throw of 82.98m"},
    "0829": {"":"", " ": "", " ":""},
    "0830": {
        "1986": "Yuriy Sedykh sets hammer throw world record with a distance of 86.74 m at the European Championships in Stuttgart, Germany",
        "1987": "Stefka Kostadinova sets the women's high jump record with a jump of 2.09m", 
        " ":""
    },
    "0831": {"":"", " ": "", " ":""},
    "0901": {
        "1947": "First modern Formula 1 Grand Prix Race in Turin, Italy. Won by Achille Varzi",
        "1974": "Mike Marshall (Dodgers) sets a major league record with his 106th pitching appearance in a season",
        "2001": "Venus Williams wins her second US Open title, defeating Serena Williams"
    },
    "0902": {
        "1984": "American Mary Lou Retton wins the Olympic individual all-around gymnastics gold medal",
        "2006": "Andre Agassi plays his last match at the US Open, losing to Benjamin Becker",
        "2018": "Novak Djokovic wins his 14th Grand Slam title at the US Open, tying Pete Sampras"
    },
    "0903": {
        "2000": "Australian Cathy Freeman lights the Olympic flame at the Sydney Olympics",
        "2006": "Roger Federer wins his third consecutive US Open title",
        "2017": "Sloane Stephens wins her first Grand Slam title at the US Open"
    },
    "0904": {
        "1972": "American Mark Spitz wins his 7th gold medal at the Munich Olympics in the 4x100m medley relay",
        "2016": "Stan Wawrinka wins his third Grand Slam title at the US Open",
        "2018": "Naomi Osaka defeats Serena Williams to win her first US Open title"
    },
    "0905": {
        "1994": "American sprinter Leroy Burrell breaks the 100m world record, running 9.85 seconds",
        "2005": "Roger Federer defeats Andre Agassi in the US Open final for his second title",
        "2009": "Kim Clijsters wins her second US Open title, becoming the first unseeded player to win since 1958"
    },
    "0906": {
        "1986": "Martina Navratilova wins her 3rd US singles title",
        "1994": "Barry Bonds becomes the fourth player in MLB history to record 40 homers and 40 steals in a season",
        "1995": "Cal Ripken Jr. plays in his 2,131st consecutive game, breaking Lou Gehrig's record"
    },
    "0907": {
        "1967": "Billie Jean King wins her first US Open title",
        "2008": "Roger Federer wins his fifth consecutive US Open title",
        "2014": "Serena Williams wins her 18th Grand Slam title at the US Open",
    },
    "0908": {
        "1968": "Arthur Ashe wins the US Open, becoming the first African American man to win the title",
        "1998": "Mark McGwire hits his 62nd home run, breaking long-standing 61 from Roger Marris",
        "2021": "Emma Raducanu wins the US Open, becoming the first qualifier to win a Grand Slam title"
    },
    "0909": {
        "2001": "Lleyton Hewitt of Australia becomes youngest (at the time) #1 male tennis player",
        "2018": "Novak Djokovic wins his 14th Grand Slam title at the US Open, tying Pete Sampras",
        "2021": "Tom Brady (Buccaneers) becomes first player to start 300 regular season NFL games"
    },
    "0910": {
        "1988": "Steffi Graf wins the US Open, completing the Golden Slam (all four Grand Slams and an Olympic gold in the same year)",
        "2005": "Kim Clijsters wins her first Grand Slam title at the US Open",
        "2022": "Carlos Alcaraz wins the US Open, becoming the youngest male to win a Grand Slam since 1990"
    },
    "0911": {
        "1985": "Pete Rose breaks Ty Cobb's all-time hits record with his 4,192nd hit",
        "2001": "Michael Jordan announces his second return to the NBA",
        "2020": "Novak Djokovic disqualified from US Open for hitting a ball out of frustration accidentally hitting a line judge"
    },
    "0912": {
        "1979": "Tracy Austin, 16, becomes the youngest US Open women's champion",
        "2004": "Roger Federer wins his first US Open title",
        "2010": "Rafael Nadal wins his first US Open title, completing the Career Grand Slam"
    },
    "0913": {
        "1991": "Kim Zmeskal is 1st American to win a medal at World Gymnastics Championships. Wins with 39.848 pts",
        "1999": "John Elway of Denver Broncos number retired #7",
        "2020": "Austrian Dominic Thiem wins his first Grand Slam title at the US Open"
    },
    "0914": {
        "1968": "Denny McLain (Tigers) wins his 30th game, the last pitcher to do so in MLB",
        "2019": "Rafael Nadal wins his 19th Grand Slam title at the US Open",
        "2021": "Daniil Medvedev wins his first Grand Slam title at the US Open"
    },
    "0915": {
        "1978": "Muhammad Ali defeats Leon Spinks to win the world heavyweight title for the third time and avenge loss",
        "2002": "Rich Gannon (Raiders) begins his record 6 straight games throwing 300 yards in the NFL",
        "2021": "Simone Biles testifies against Gymnastics Doctor and rapist Larry Nassar"
    },
    "0916": {
        "1924": "Jim Bottomley (Cardinals) sets a record with 12 RBIs in a single game",
        "1995": "Greg Maddux (Braves) sets record 17 straight road game pitching victories",
        "2018": "Land speed cycling record broken in Utah by Denise Mueller-Korenek. Bikes an average of 184mph (296km/h)"
    },
    "0917": {
        "2000": "NFL's Dan Marino (Dolphins) number retired #13",
        "2004": "Barry Bonds (Giants) hits his 700th home run off Jake Peavy",
        "2013": "Marian Hossa of the Chicago Blackhawks plays his 1,000th NHL game"
    },
    "0918": {
        "1994": "First Presidents Cup Golf US beats the International team 20-12",
        "1927": "Columbia University football team plays its first game at the new Baker Field stadium",
        "1954": "Rocky Marciano knocks out Ezzard Charles to retain the world heavyweight title",
        "1966": "Richie Allen hits the longest home run in the history of Connie Mack Stadium",
        "1983": "Carl Lewis wins the gold medal in the long jump at the World Championships",
        "1988": "Greg Louganis wins gold in the 3-meter springboard diving at the Seoul Olympics",
        "1999": "Serena Williams wins her first Grand Slam title at the US Open",
        "2005": "Fernando Alonso wins the Formula 1 World Championship",
        "2020": "Dustin Johnson wins the FedEx Cup, his first career PGA Tour season title"
    },
    "0919": {
        "1955": "Rocky Marciano knocks out Archie Moore to retain the world heavyweight title",
        "1968": "Bob Beamon breaks the world record in the long jump at the Mexico City Olympics",
        "1973": "Billie Jean King defeats Bobby Riggs in the 'Battle of the Sexes' tennis match",
        "1981": "Boris Becker wins his first Grand Slam title at Wimbledon",
        "2004": "Roger Federer wins his first US Open title",
        "2005": "Lance Armstrong wins his seventh consecutive Tour de France",
        "2017": "Rafael Nadal wins his 16th Grand Slam title at the US Open",
        "2019": "Simona Halep wins her first Wimbledon title"
    },
    "0920": {
        "1988": "USSR team sets the women's 4x100m relay record with a time of 40.82",
        "":"",
        " ":""
    },
    "0921": {"":"", " ": "", " ":""},
    "0922": {"":"", " ": "", " ":""},
    "0923": {"":"", " ": "", " ":""},
    "0924": {"1988": "Jackie Joyner-Kersee sets the women's heptathlon record with 7291 points", " ": "", " ":""},
    "0925": {"":"", " ": "", " ":""},
    "0926": {"":"", " ": "", " ":""},
    "0927": {"":"", " ": "", " ":""},
    "0928": {"":"", " ": "", " ":""},
    "0929": {
        "1977": "Pele plays his final game for the New York Cosmos in an exhibition against Santos",
        "1988": "Florence Griffith Joyner sets the women's 200m record with a time of 21.34s", " ":""},
    "0930": {"":"", " ": "", " ":""},
    "1001": {"":"", " ": "", "2023": "Diribe Welteji sets the women's road mile record with a time of 4:20.98"},
    "1002": {
        "1968": "Bob Gibson sets a World Series record with 17 strikeouts in a single game",
        " ": "", " ":""},
    "1003": {
        "1992": "Maurizio Damilano sets 2 hours walk (track) world record with a distance of 29,572 m and 30,000 m walk (track) world record with a time of 2:01:44.1 in Cuneo, Italy",
        " ":"",
        "  ":""
    },
    "1004": {"":"", " ": "", " ":""},
    "1005": {"":"", " ": "", " ":""},
    "1006": {"1985": "Marita Koch sets the women's 400m record with a time of 47.60s", 
        "1996":"Tiger Woods wins first PGA Tour event, the Las Vegas Invitational", 
        " ":""},
    "1007": {"":"", " ": "", " ":""},
    "1008": {"":"", " ": "", " ":""},
    "1009": {"":"", " ": "", " ":""},
    "1010": {"":"", " ": "", " ":""},
    "1011": {"":"", " ": "", " ":""},
    "1012": {"":"", " ": "", " ":""},
    "1013": {"":"", " ": "", " ":""},
    "1014": {"":"", " ": "", " ":""},
    "1015": {"":"", " ": "", " ":""},
    "1016": {"":"", " ": "", " ":""},
    "1017": {"":"", " ": "", " ":""},
    "1018": {"":"", " ": "", " ":""},
    "1019": {"":"", " ": "", " ":""},
    "1020": {"":"", " ": "", " ":""},
    "1021": {"":"", " ": "", " ":""},
    "1022": {"":"", " ": "", " ":""},
    "1023": {"":"", " ": "", " ":""},
    "1024": {"":"", " ": "", "2021": "Letesenbet Gidey sets the women's half marathon record with a time of 1:05:16"},
    "1025": {"":"", " ": "", " ":""},
    "1026": {"":"", " ": "", " ":""},
    "1027": {"":"", " ": "", " ":""},
    "1028": {"":"", " ": "", " ":""},
    "1029": {"":"", " ": "", " ":""},
    "1030": {"":"", " ": "", " ":""},
    "1031": {"":"", " ": "", " ":""},
    "1101": {"":"", " ": "", " ":""},
    "1102": {"":"", " ": "", " ":""},
    "1103": {"":"", " ": "", " ":""},
    "1104": {"":"", " ": "", " ":""},
    "1105": {"":"", " ": "", " ":""},
    "1106": {"":"", " ": "", " ":""},
    "1107": {"":"", " ": "", " ":""},
    "1108": {"":"", " ": "", " ":""},
    "1109": {"":"", " ": "", " ":""},
    "1110": {"":"", " ": "", " ":""},
    "1111": {"":"", " ": "", " ":""},
    "1112": {"":"", " ": "", " ":""},
    "1113": {"":"", " ": "", " ":""},
    "1114": {"":"", " ": "", " ":""},
    "1115": {"":"", " ": "", " ":""},
    "1116": {"":"", " ": "", " ":""},
    "1117": {"":"", " ": "", " ":""},
    "1118": {"":"", " ": "", " ":""},
    "1119": {"":"", " ": "", " ":""},
    "1120": {"":"", " ": "", " ":""},
    "1121": {"":"", " ": "", " ":""},
    "1122": {"":"", " ": "", " ":""},
    "1123": {
        "2005": "Josephat Ndambiri, Martin Mathathi, Daniel Muchunu Mwangi, Mekubo Mogusu, Onesmus Nyerre, and John Kariuki set road relay 42.195 km world record with a time of 1:57:06 at the Chiba Ekiden in Chiba, Japan",
        " ":"",
        "  ":""
    },
    "1124": {"":"", " ": "", " ":""},
    "1125": {"":"", " ": "", " ":""},
    "1126": {"":"", " ": "", " ":""},
    "1127": {"":"", " ": "", " ":""},
    "1128": {"":"", " ": "", " ":""},
    "1129": {"":"", " ": "", " ":""},
    "1130": {"":"", " ": "", " ":""},
    "1201": {"":"", " ": "", " ":""},
    "1202": {"":"", " ": "", " ":""},
    "1203": {"":"", " ": "", " ":""},
    "1204": {"":"", " ": "", " ":""},
    "1205": {"":"", " ": "", " ":""},
    "1206": {"":"", " ": "", " ":""},
    "1207": {"":"", " ": "", " ":""},
    "1208": {"":"", " ": "", " ":""},
    "1209": {"":"", " ": "", " ":""},
    "1210": {"":"", " ": "", " ":""},
    "1211": {"":"", " ": "", " ":""},
    "1212": {"":"", " ": "", " ":""},
    "1213": {"":"", " ": "", " ":""},
    "1214": {"":"", " ": "", " ":""},
    "1215": {"":"", " ": "", " ":""},
    "1216": {"":"", " ": "", " ":""},
    "1217": {"":"", " ": "", " ":""},
    "1218": {"":"", " ": "", " ":""},
    "1219": {"":"", " ": "", " ":""},
    "1220": {"":"", " ": "", " ":""},
    "1221": {"":"", " ": "", " ":""},
    "1222": {"":"", " ": "", " ":""},
    "1223": {"":"", " ": "", " ":""},
    "1224": {"":"", " ": "", " ":""},
    "1225": {"":"", " ": "", " ":""},
    "1226": {"":"", " ": "", " ":""},
    "1227": {"":"", " ": "", " ":""},
    "1228": {"":"", " ": "", " ":""},
    "1229": {"":"", " ": "", " ":""},
    "1230": {"":"", " ": "", " ":""},
    "1231": {"":"", " ": "", "2023": "Beatrice Chebet sets the women's 5km road record with a time of 14:13"}
    
    
}